### ISSUE TITLE
Hadoop

### ISSUE THREAD

**Issue by npinto** [jtriley/StarCluster#1]
Would it be possible to have Hadoop installed on a StarCluster ? Something like what Cloudera has would be wonderful ;-)

Thanks in advance.

Nicolas

**Comment by jtriley** [comment]
yep, this will be included as a plugin

**Comment by jtriley** [comment]
There is now a plugin in the StarClusterPlugins project for hadoop: 

http://github.com/jtriley/StarClusterPlugins

Currently you need the latest development version of StarCluster to use the plugin. There are three AMIs available with the cloudera hadoop packages installed:

32bit:
ami-1e4dbf77 us-east-1 starcluster-base-ubuntu-10.04-x86-hadoop-rc4-ebs (EBS)

64bit:
ami-8852a0e1 us-east-1 starcluster-base-ubuntu-10.04-x86_64-hadoop
ami-06a75a6f us-east-1 starcluster-base-centos-5.4-x86_64-ebs-hvm-gpu-hadoop-rc2 (HVM-EBS)
