### ISSUE TITLE
wait_for_active_spots queries for spot instance requests too quickly

### ISSUE THREAD

**Issue by jtriley** [jtriley/StarCluster#105]
From the mailing list:

http://mailman.mit.edu/pipermail/starcluster/2012-April/001146.html

From my testing, wait_for_active_spots queries all cluster spot requests
immediately after creating them. In some cases this happens before they're
available via the AWS API which causes the code to move past waiting for active
spot requests given that it appears that there aren't any spot requests.

**Comment by FinchPowers** [comment]
Fixed by pull request https://github.com/jtriley/StarCluster/pull/163
