### ISSUE TITLE
nfs shares of EBS volumes duplicated

### ISSUE THREAD

**Issue by jschug** [jtriley/StarCluster#106]
Using ami-999d49f0 for master and nodes and mounting two EBS volumes I see this correct df -h on the master:

/dev/xvdz1            985G  293G  642G  32% /data
/dev/xvdy1            985G   67G  868G   8% /combo

but see this on the nodes:

master:/data          985G  293G  642G  32% /data
master:/combo         985G  293G  642G  32% /combo

Apparent contents of /combo on nodes are what's in /data.

A umount and remount does not help.

**Comment by jtriley** [comment]
Can you send me the contents of /etc/exports on the master node and /etc/fstab on a worker node?

**Comment by jschug** [comment]
They look right to me - mysterious.

/home node001(async,no_root_squash,no_subtree_check,rw)
/data node001(async,no_root_squash,no_subtree_check,rw)
/combo node001(async,no_root_squash,no_subtree_check,rw)
/home node002(async,no_root_squash,no_subtree_check,rw)
/data node002(async,no_root_squash,no_subtree_check,rw)
/combo node002(async,no_root_squash,no_subtree_check,rw)
/opt/sge6 node001(async,no_root_squash,no_subtree_check,rw)
/opt/sge6 node002(async,no_root_squash,no_subtree_check,rw)

and

LABEL=cloudimg-rootfs   /    ext4   defaults    0 0
/dev/xvdb1  /mnt    auto    defaults,nobootwait,comment=cloudconfig 0   2
master:/home /home nfs vers=3,user,rw,exec,noauto 0 0
master:/data /data nfs vers=3,user,rw,exec,noauto 0 0
master:/combo /combo nfs vers=3,user,rw,exec,noauto 0 0
master:/opt/sge6 /opt/sge6 nfs vers=3,user,rw,exec,noauto 0 0

**Comment by jtriley** [comment]
Yea that looks fine at first glance. Are you able to reproduce this after a relaunch? I'll try to test this myself later today.

**Comment by jschug** [comment]
I got this a few times using a couple of different ami's for the master and nodes.  Initially I had the vols mounted at /vols/data and /vols/combo and thought the common path might be a problem, but it wasn't.  I think this happened about 4 times and I could not get rid of it, so am using just one disk as a work-around until it's fixed. Thanks for looking into it.

**Comment by jtriley** [comment]
@jschug Just for drill: can you paste your volume config?

**Comment by jtriley** [comment]
@jschug are you still having this issue?

**Comment by jtriley** [comment]
@jschung StarCluster 0.94 has been released. Please retest with 0.94 and reopen if you're able to reproduce this issue.
