### ISSUE TITLE
Add option to forward authentication agent to sshmaster

### ISSUE THREAD

**Issue by daviderickson** [jtriley/StarCluster#128]
As the title says, it would be really nice to be able to forward my auth agent using ssh(instance|node|master).  And in general it would be even better if I could pass through arbitrary ssh arguments using these starcluster commands.

**Comment by jtriley** [comment]
Just for the record, this was completed thanks to @daviderickson in 7d0b793e837efdaa62fa836428cd4f1393118b7d
