### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by ablimit** [jtriley/StarCluster#138]
After installation, I typed starcluster, and the following error appeared on the screen ? 

ImportError: /usr/local/lib/python2.6/dist-packages/pycrypto-2.6-py2.6-linux-x86_64.egg/Crypto/Cipher/_AES.so: undefined symbol: rpl_malloc

**Comment by jtriley** [comment]
It looks like PyCrypto's _AES.so is linked to a library during installation that it later cannot find in your current environment. If you could run `ldd` on _AES.so and post the output that'd be helpful:

```
ldd /usr/local/lib/python2.6/dist-packages/pycrypto-2.6-py2.6-linux-x86_64.egg/Crypto/Cipher/_AES.so
```

Thanks!

**Comment by jtriley** [comment]
Doing a little more research I found a blog post where they were having issues using PyCrypto (ironically on Amazon EC2):

http://bugcharmer.blogspot.com/2012/07/building-pycrypto-on-amazon-ec2.html

After reading that post I believe you can fix this by doing:

$ export ac_cv_func_malloc_0_nonnull = yes

and then forcing a reinstall of PyCrypto:

$ easy_install -U PyCrypto

Let me know if that fixes things for you.

**Comment by ablimit** [comment]
Awesome. That works. 
Many thanks, Justin.

**Comment by jsfs2019** [comment]
thx so much!!!

**Comment by foreverhj** [comment]
thx jtriley
I try 
$ export ac_cv_func_malloc_0_nonnull=yes
$ easy_install -U PyCrypto
and it works.
