### ISSUE TITLE
pkginstaller plugin should run BEFORE the node is added to the SGE

### ISSUE THREAD

**Issue by turian** [jtriley/StarCluster#139]
The pkginstaller plugin should run BEFORE the node is added to the SGE.

The reason is simple:

pkginstaller is used to specify packages that the nodes require.
If the node is in the SGE before the packages are installed, it will accept jobs and fail on them.

**Comment by jtriley** [comment]
@turian Yes, historically SGE has been a 'default' plugin. In the future I'll likely disable SGE by default (after some releases that warn loudly about this) and let users configure it as a plugin if they need it. For now you can disable SGE and then put it in the correct order in your plugins list, e.g.:

```
[plugin pkginstaller]
setup_class = starcluster.plugins.pkginstaller.PackageIntaller
packages = pkg1, pkg2

[plugin sge]
setup_class = starcluster.plugins.sge.SGEPlugin

[cluster smallcluster]
...
disable_queue = True
plugins = pkginstaller, sge
```

See http://star.mit.edu/cluster/docs/latest/plugins/sge.html#advanced-options for more details. Hope that helps!

**Comment by jtriley** [comment]
Closing this given that there is a suitable workaround and the issue of eventually removing SGE from the default plugins is well known. Feel free to continue to comment on this bug if you still have issues setting up the config to do what you want.
