### ISSUE TITLE
S3 SSL validation fails

### ISSUE THREAD

**Issue by ghost** [jtriley/StarCluster#141]
When I use http_validate_certificates = True, I get the following exception:

```
InvalidCertificateException: Host mybucket.s3.amazonaws.com returned an invalid certificate (remote hostname "mybucket.s3.amazonaws.com" does not match certificate): {'notAfter': 'Dec 18 23:59:59 2013 GMT', 'subjectAltName': (('DNS', '*.s3.amazonaws.com'), ('DNS', 's3.amazonaws.com')), 'subject': ((('countryName', u'US'),), (('stateOrProvinceName', u'Washington'),), (('localityName', u'Seattle'),), (('organizationName', u'Amazon.com Inc.'),), (('commonName', u'*.s3.amazonaws.com'),))}
```

when getting a bucket using an S3Connection. It does work though if I use a URI object created with boto.storage_uri.

**Comment by jtriley** [comment]
@johnwulf Thanks for reporting. Which version of boto are you using? IMO this is ultimately a bug with boto but I could be wrong. In either case I'm interested in fixing it if possible. I'm curious if it happens with the latest boto. If you try the latest github code (https://github.com/jtriley/StarCluster/zipball/master) that should pull in the latest version of boto (currently 2.5.2).

**Comment by jtriley** [comment]
FWIW I have http_validate_certificates=True in my ~/.boto and I can successfully fetch a bucket from S3Connection without that error using boto 2.5.2...

**Comment by jtriley** [comment]
I'm going to close this issue for now given that it's purely boto related and it seems to work fine for me with latest boto 2.5.2. Please feel free to reopen if you're still having issues with the latest boto 2.5.2 version but at that point I'd recommend also filing a bug with boto.

**Comment by ghost** [comment]
I am using boot 2.5.2 too and I get it to work when I gt a bucket through an uri constructed through the storage_uri, but if I create a connection myself and try to get the bucket, I gt that error. I will hunt that a more down on the weekend and see what the issue is.

**Comment by jtriley** [comment]
Ok, can you please paste the entire stacktrace and not just the exception message? Also what does your ~/.boto file look like? Perhaps @garnaat and his team have an idea? BTW it should be https_validate_certificates (not http_validate_certificates). In any event I would recommend filing a bug with boto with more details about OS, Python version, etc. In the mean time you're welcome to jump on #starcluster on IRC (freenode) and try to debug...

**Comment by garnaat** [comment]
This is complicated 8^(

By default, boto uses what we refer to as the SubdomainCallingFormat which is the recommended way to address buckets in S3.  In this calling format, the Host header in the request includes the bucket name as a subdomain.  So, if your bucket name is "foobar", the Host header becomes:

```
Host: foobar.s3.amazonaws.com
```

S3 has wildcard SSL certs on all of their endpoints so trying to validate this hostname against the SSL cert will work correctly.

However, if your bucket name has periods in it, i.e. "foo.bar" then the hostname becomes:

```
Host: foo.bar.s3.amazonaws.com
```

and the wildcard cert will only match one level of subdomain names.  Therefore, the cert verification fails.

There are two ways to fix this problem.  The first is to disable cert verfication.  The second is to tell boto to use the OrdinaryCallingFormat rather than the SubdomainCallingFormat.  You can do this via:

```
>>> import boto
>>> from boto.s3.connection import OrdinaryCallingFormat
>>> c = boto.connect_s3(..., calling_format=OrdinaryCallingFormat(),...)
```

Hope that helps!

**Comment by jtriley** [comment]
@garnaat Awesome, thanks for pointing that out. The original error @johnwulf posted showed the bucket as 'mybucket' but I'm guessing he's hiding the real bucket name which likely contains periods (I find it hard to imagine 'mybucket' wasn't already taken anyway...)

**Comment by ghost** [comment]
That is the case. There are dots in the bucket name and I was hiding it, not in a good way. So much about me being precise when stating things or reading the damn manual. I was suspecting something like this, but didn't have the time to test it (not enough hours during the day), as it was working through using storage_uri. Anyways, this is all proper behavior, as you pointed out.

Appreciate your time and help.
