### ISSUE TITLE
Add option to bail out if EBS volume can't be mounted

### ISSUE THREAD

**Issue by jairideout** [jtriley/StarCluster#143]
Sometimes creating a new cluster with an EBS volume will fail to attach the volume because the volume's device cannot be found. This is printed out as a warning, but the cluster continues to be created.

Would it be possible to add an option to 'starcluster start' to have it error out if the EBS volume cannot be attached? Or more generally, to bail out if any warnings are encountered in the cluster setup process? This would make things a bit easier on us, at least for how we're using starcluster.

**Comment by jtriley** [comment]
Yea, the default behavior should probably be to just bail on any error encountered during setup and add a flag for those that want to 'force' things...

**Comment by jtriley** [comment]
Changing the code now to always raise an exception whenever a command fails to execute (unless ignore_exit_status=True or raise_on_failure=False)...
