### ISSUE TITLE
StarCuster client writes a config template with world-readable permissions

### ISSUE THREAD

**Issue by spacepod** [jtriley/StarCluster#144]
(At least on OS X 10.8), on an initial run of the StarCluster commandline client, after accepting the  option to write the .starcluster/config template, the config file is left world-readable.  I suggest that this should be changed to be only readable by the user (chmod go-rwx ) for security issues, as this file contains the user's AWS access and secret key. 

```
!!! ERROR - config file /Users/natalie/.starcluster/config does not exist

Options:
--------
[1] Show the StarCluster config template
[2] Write config template to /Users/natalie/.starcluster/config
[q] Quit

Please enter your selection: 2

>>> Config template written to /Users/natalie/.starcluster/config
>>> Please customize the config template

$ ls -la .starcluster/config 
-rw-r--r--  1 natalie  staff  12106 Oct  8 11:01 .starcluster/config
```

**Comment by jtriley** [comment]
Good call, fixing this now. Thanks for reporting.

**Comment by jtriley** [comment]
My apologies for taking forever on this, Thanks again for reporting!
