### ISSUE TITLE
Cluster started with 0.93 cannot be terminated with 0.999

### ISSUE THREAD

**Issue by jstjohn** [jtriley/StarCluster#151]
I tried to do a starcluster terminate on a cluster started with v 0.93 after upgrading to the development version. However when I do this I get the following error:

```
!!! ERROR - failed to load cluster receipt: Not a gzipped file
```

**Comment by jtriley** [comment]
Yes, the next version of StarCluster (in development) will not be compatible with clusters created with older (0.93.x) StarCluster versions. You'll need to temporarily switch to 0.93.3 to terminate your old clusters before using the latest development version. I will add sufficient warnings before the next release as I've done in the past when these sort of changes occur..
