### ISSUE TITLE
Dangling threads on_add_node, on_remove_node

### ISSUE THREAD

**Issue by scrappythekangaroo** [jtriley/StarCluster#159]
Anybody else notice that these methods seen to leave dangling threadpools?  Seems to be a problem when using the load balancer whenever a node is added/removed since the number of threads attached to the load balancer can quickly explode.

Any reason why on_add_node, on_remove_node don't contain:
try:
   ...
finally:
   self.pool.shutdown()

as in the run method?

**Comment by jtriley** [comment]
This should be fixed in the next 0.94 release. Fix has been merged to the develop branch.
