### ISSUE TITLE
Thread leak

### ISSUE THREAD

**Issue by FinchPowers** [jtriley/StarCluster#177]
I've got a load balancer crash due to an "error: out of threads"

I think the Cluster.add_nodes leaks threads.

```
821: default_plugin = clustersetup.DefaultClusterSetup(...
```

a new DefaultClusterSetup is created. Then add_node

```
828: default_plugin.on_add_node(...
```

Then in clustersetup.on_add_node

```
394: self._setup_hostnames(nodes=[node])
```

Creates the thread pool. (In fact a bunch of functions here would create it, it's simply a matter of the first needing it creates it.)

And then back to our Cluster.add_nodes context, the pool is not cleared. If I'm not mistaken, It means that every time we add a node, we leak threads.

**Comment by FinchPowers** [comment]
I've made a fix attempt https://github.com/datacratic/StarCluster/tree/177_thread_leak
I'll see how it goes.

**Comment by jtriley** [comment]
Thanks for reporting, working on a fix for this now.
