### ISSUE TITLE
addnode NFS doesn't respect MOUNT_POINT

### ISSUE THREAD

**Issue by dpolhamus** [jtriley/StarCluster#179]
The desired behavior is seen when starting a cluster of multiple nodes (starcluster start -s x myCluster), NFS shares MOUNT_POINT to each node.  However, when using starcluster addnode, MOUNT_POINT is disregarded and /home is shared instead.

**Comment by jtriley** [comment]
Are you using 0.93.3 or the latest github version?

**Comment by dpolhamus** [comment]
Hi Justin, this is the latest github version.
Dan

On Mon, Nov 26, 2012 at 3:22 PM, Justin Riley notifications@github.comwrote:

> Are you using 0.93.3 or the latest github version?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jtriley/StarCluster/issues/179#issuecomment-10732093.

## 

Daniel G Polhamus, PhD
Metrum Research Group, LLC
2 Tunxis Rd, Suite 112
Tariffville, CT 06081
(888) 308-7049 ext 403

**Comment by jtriley** [comment]
@drexell0680 OK, this is due to some recent refactorings. Should have a fix soon. Thanks for reporting!
