### ISSUE TITLE
starcluster createvolume fails due to -F option

### ISSUE THREAD

**Issue by marktsuchida** [jtriley/StarCluster#181]
This command fails:
`starcluster createvolume -n my-volume -m mkfs.reiserfs 10 us-east-1a`

(`mkfs.reiserfs` is not installed on the default image, so I sshed into it and did `apt-get reiserfsprogs`, but that is not the main problem here.)

StarCluster tries to execute `mkfs.reiserfs -F /dev/xvdx`, but this fails because `mkfs.reiserfs` does not understand the `-F` option (`mkfs.reiserfs -ff ...` or `yes | mkfs.reiserfs ...` is what is wanted).

It's easy enough to work around (ssh and run `mkfs.reiserfs` manually), of course.

**Comment by marktsuchida** [comment]
Well, it looks like the default image cannot mount ReiserFS volumes anyway, so I'm going to close this.

**Comment by jtriley** [comment]
@marktsuchida Yea, sorry about that. I've included more filesystem utilties in the new 12.04 AMIs that will be public soon but in the mean time you can update the latest 12.04 AMIs using ebsimage command. See:

http://star.mit.edu/cluster/docs/latest/manual/create_new_ami.html

I just fixed the issue you were having with the '-F' option. It's no longer used by default and is only used with mkfs.ext3.

**Comment by marktsuchida** [comment]
@jtriley Thanks!

**Comment by jtriley** [comment]
@marktsuchida Thanks for reporting!
