### ISSUE TITLE
Remove configuration data from security group description

### ISSUE THREAD

**Issue by somerandomsequence** [jtriley/StarCluster#193]
It seems to me that this is a bad place to store configuration data, given that it is immutable (if you want to change it, you must first destroy all the instances associated with it and recreate them with a new security group), and it is seemingly quite esoteric (it took me some time to discover the data there, and longer to find the pieces of code that decode, uncompress, and de-Pickle it). 

Storing variables in the "cloud" like this takes the concept of global variables to a whole new level :/.

For me, it created issues when I tried to move the cluster to a different account and found that this pickled configuration still referenced a volume from the past account.

Here is a patch providing a dirty hack to move this configuration data into .starcluster/pickle. IMHO, a better solution would be to keep /all/ the configuration data in one place (.starcluster/config), but this at least fixed my problem.

``` diff
diff -u starcluster.dist/cluster.py /usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/cluster.py
--- starcluster.dist/cluster.py 2012-10-31 03:47:32.929627655 +0000
+++ /usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/cluster.py    2012-12-19 14:56:31.511814087 +0000
@@ -552,16 +552,15 @@
         """
         try:
             desc = self.cluster_group.description
-            version, b64data = desc.split('-', 1)
+            version = desc
             if utils.program_version_greater(version, static.VERSION):
                 d = dict(cluster=self.cluster_tag, old_version=static.VERSION,
                          new_version=version)
                 msg = user_msgs.version_mismatch % d
                 sep = '*' * 60
                 log.warn('\n'.join([sep, msg, sep]), extra={'__textwrap__': 1})
-            compressed_data = base64.b64decode(b64data)
-            pkl_data = zlib.decompress(compressed_data)
-            cluster_settings = cPickle.loads(str(pkl_data)).__dict__
+            cluster_settings = cPickle.load(open(static.STARCLUSTER_PKL_FILE,"rb")).__dict__
+            pprint.pprint(cluster_settings)
         except (cPickle.PickleError, zlib.error, ValueError, TypeError,
                 EOFError, IndexError), e:
             log.debug('load receipt exception: ', exc_info=True)
@@ -606,8 +605,7 @@
     def cluster_group(self):
         if self._cluster_group is None:
             ssh_port = static.DEFAULT_SSH_PORT
-            desc = base64.b64encode(zlib.compress(cPickle.dumps(self)))
-            desc = '-'.join([static.VERSION, desc])
+            desc = static.VERSION
             sg = self.ec2.get_or_create_group(self._security_group,
                                               desc,
                                               auth_ssh=True,
Common subdirectories: starcluster.dist/commands and /usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/commands
Common subdirectories: starcluster.dist/plugins and /usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/plugins
Common subdirectories: starcluster.dist/sshutils and /usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/sshutils
diff -u starcluster.dist/static.py /usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/static.py
--- starcluster.dist/static.py  2012-10-31 03:47:32.925627654 +0000
+++ /usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/static.py 2012-12-19 14:27:49.987412204 +0000
@@ -46,6 +46,7 @@

 STARCLUSTER_CFG_DIR = os.path.join(os.path.expanduser('~'), '.starcluster')
 STARCLUSTER_CFG_FILE = os.path.join(STARCLUSTER_CFG_DIR, 'config')
+STARCLUSTER_PKL_FILE = os.path.join(STARCLUSTER_CFG_DIR, 'pickle')
 STARCLUSTER_PLUGIN_DIR = os.path.join(STARCLUSTER_CFG_DIR, 'plugins')
 STARCLUSTER_LOG_DIR = os.path.join(STARCLUSTER_CFG_DIR, 'logs')
 STARCLUSTER_RECEIPT_DIR = "/var/run/starcluster"
Common subdirectories: starcluster.dist/templates and /usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/templates
Common subdirectories: starcluster.dist/tests and /usr/lib/python2.6/site-packages/StarCluster-0.93.3-py2.6.egg/starcluster/tests
```

P.S. Pickles-in-the-cloud not withstanding, Starcluster is absolutely fantastic! Thank you so much!

**Comment by FinchPowers** [comment]
Then you won't have a choice but to control your cluster from the same server.

What config are you trying to change? I've made a patch (yet to be merged) that allows to reload config. See https://github.com/datacratic/StarCluster/tree/dev_config_fcts or pr https://github.com/jtriley/StarCluster/pull/162

**Comment by somerandomsequence** [comment]
I needed to point cluster_data['volumes']['myvolume']['volume_id'] to the new volume ID (it was referencing an EBS volume associated with the old account).

Doing a 'removevolume' and a 'createvolume' might have worked too, but I wasn't able to try this since I kept getting errors about the old volume (still referenced in the pickle) not existing.

**Comment by FinchPowers** [comment]
Ok I don't my patch covers that case.

**Comment by jtriley** [comment]
The latest code now stores this information in more common locations: tags and userdata. I agree with you that it's some what creepy to store cluster settings in the cloud but the reason is so that you can use StarCluster between machines without needing the original config file. If two users attempt to run operations on a cluster without the same cluster settings loaded you could potentially wind up damaging the cluster. I've moved this data from the description field, which was always a hack that relied on the fact that security group description's apparently have no limit to their value, however, storing the cluster's configuration at some 'global' level within the AWS API is still important for the multiple users case.

Also, keep in mind that the cluster 'templates' in ~/.starcluster/config are not directly tied to any given cluster in the sense that you can use a single cluster 'template' in the config to create multiple clusters. The name of a given cluster on EC2 is independent of the cluster settings used in the config file. This avoids users having to keep updating ~/.starcluster/config with duplicate cluster configs if they want to launch 5 different clusters using the same settings for example.

The latest code stores most of the cluster configuration in security group tags, however, there's a 10 tag limit with each tag value limited to 255 chars so not everything fits there - especially config items that allow specifying multiple items such as volumes and plugins. These two settings in particular could potentially be very large depending how many plugins/volumes are in play so they can not reliably be stored in cluster tags and instead must live in the (immutable) userdata of the master node. This unfortunately still does not meet your use case of moving a cluster as-is.

With all that said, how are you going about moving the cluster between accounts exactly? In general I would suggest terminating and using the same config to bring everything back up on the new account if possible.

**Comment by somerandomsequence** [comment]
Sorry for the delayed response, I was travelling for the holidays and
didn't have a computer handy.

I moved the cluster by: 1) creating an AMI for each cluster node (and the
client node) 2) sharing those AMIs with the new account 3) instantiating
them in the new account, and carefully copying the user data, tags, and
security group configuration 4) re-creating the EBS volumes (with the same
names and whatnot).

After using my hack to update the pickled data in the security group
description (particularly, the volume IDs needed to be updated), everything
appears to work. Although a bit laborious, this route worked and allowed me
to avoid reinstalling/compiling custom software on new nodes (which, even
when done in parallel, takes a long time).

## 

Caleb

On Thu, Dec 27, 2012 at 4:15 PM, Justin Riley notifications@github.comwrote:

> The latest code now stores this information in more common locations: tags
> and userdata. I agree with you that it's some what creepy to store cluster
> settings in the cloud but the reason is so that you can use StarCluster
> between machines without needing the original config file. If two users
> attempt to run operations on a cluster without the same cluster settings
> loaded you could potentially wind up damaging the cluster. I've moved this
> data from the description field, which was always a hack that relied on the
> fact that security group description's apparently have no limit to their
> value, however, storing the cluster's configuration at some 'global' level
> within the AWS API is still important for the multiple users case.
> 
> Also, keep in mind that the cluster 'templates' in ~/.starcluster/config
> are not directly tied to any given cluster in the sense that you can use a
> single cluster 'template' in the config to create multiple clusters. The
> name of a given cluster on EC2 is independent of the cluster settings used
> in the config file. This avoids users having to keep updating
> ~/.starcluster/config with duplicate cluster configs if they want to launch
> 5 different clusters using the same settings for example.
> 
> The latest code stores most of the cluster configuration in security group
> tags, however, there's a 10 tag limit with each tag value limited to 255
> chars so not everything fits there - especially config items that allow
> specifying multiple items such as volumes and plugins. These two settings
> in particular could potentially be very large depending how many
> plugins/volumes are in play so they can not reliably be stored in cluster
> tags and instead must live in the (immutable) userdata of the master node.
> This unfortunately still does not meet your use case of moving a cluster
> as-is.
> 
> With all that said, how are you going about moving the cluster between
> accounts exactly? In general I would suggest terminating and using the same
> config to bring everything back up on the new account if possible.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jtriley/StarCluster/issues/193#issuecomment-11721004.

## 

Caleb

**Comment by jtriley** [comment]
Wow, that's quite a lot of work but glad you got it working. Unfortunately moving a cluster this way is completely unsupported so I've closed this issue. In the future I would recommend just creating a single custom AMI with all your custom software compiled given that it takes too long to do on start-up. Then you would have been able to move the cluster to another account by:
1. Saving everything to EBS and snapshot the volumes
2. Share the snapshots with the new account and recreate the volumes in the new account
3. Update the config with the new account creds, your custom AMI, and new volume ids
4. Relaunch the cluster with the start command on the new account
