### ISSUE TITLE
couchdb

### ISSUE THREAD

**Issue by npinto** [jtriley/StarCluster#2]
Would it be possible to get couchdb-0.10.X installed on the server node and a ssh tunnel on each node (ssh -f -N -L 5984:localhost:5984 master) ?

Thanks in advance.

Nicolas

**Comment by npinto** [comment]
Here is a (non-fully tested) way of installing couchdb 0.10 on Ubuntu 9.10:

# some preparation

sudo apt-get install build-essential erlang

export PREFIX=/usr
mkdir -p $HOME/src && cd $HOME/src

# spidermonkey js

wget http://ftp.mozilla.org/pub/mozilla.org/js/js-1.8.0-rc1.tar.gz
tar zxf js-1.8.0-rc1.tar.gz
cd js/src
make BUILD_OPT=1 -f Makefile.ref
sudo mkdir -p $PREFIX/include/js
sudo mkdir -p $PREFIX/include/js
sudo cp -v _.{h,tbl} $PREFIX/include/js/
sudo cp -v Linux_All_OPT.OBJ/_.h $PREFIX/include/js/
sudo cp -v Linux_All_OPT.OBJ/js $PREFIX/bin/
sudo cp -v Linux_All_OPT.OBJ/libjs.so $PREFIX/lib/

# couchdb 0.10

cd $HOME/src
wget http://www.alliedquotes.com/mirrors/apache/couchdb/0.10.0/apache-couchdb-0.10.0.tar.gz
tar xzvf apache-couchdb-0.10.0.tar.gz
cd apache-couchdb-0.10.0
./configure --prefix=$PREFIX

make -j 8

sudo make install

**Comment by jtriley** [comment]
This should probably be added to the StarClusterPlugins project. Are you still using couchdb or mongodb these days?

**Comment by npinto** [comment]
I'm using mongo now ;-)

**Comment by jtriley** [comment]
OK, I'm going to close this issue and open a new issue on StarClusterPlugins for a mongodb plugin. Does that work for you?

**Comment by npinto** [comment]
Sounds good, thanks again!
