### ISSUE TITLE
hs1.8xlarge only mounting 4 of the 24 instance stores

### ISSUE THREAD

**Issue by jstjohn** [jtriley/StarCluster#202]
When I launch an hs1.8xlarge instance, it should have 24 2TB drives available in /dev. However there are only 4 that show up. I confirmed that this is the case with AWS support. When you launch the starcluster AMI from the web console though, it comes up with all 24 drives mounted.

Starcluster or boto must not be doing the same kinds of steps to make sure that all drives that need to be mounted are mounted. I am not sure what the workaround is for this. The AWS support people recommended booting up an instance from the web console and taking an image of it from there. Then maybe when it is booted up in the future from the `starcluster` console, it might work. I have not yet tested this theory.

**Comment by egafni** [comment]
I also ran into this problem, and monkey patched my code to get around this.  

The problem is that starcluster.awsutils run_instances is not passing a BlockDeviceMap to boto.ec2.connection.run_instances().  

Here's how I modified the awsutils.run_instances method

```
def run_instances(self, image_id, instance_type='m1.small', min_count=1,
                  max_count=1, key_name=None, security_groups=None,
                  placement=None, user_data=None, placement_group=None):

    #modifications by Erik
    if instance_type == 'hs1.8xlarge':
        from boto.ec2.blockdevicemapping import BlockDeviceType, BlockDeviceMapping
        map = BlockDeviceMapping()
        for i in range(0,24):
            t = BlockDeviceType()
            t.virtual_name = 'ephemeral{0}'.format(i)
            map['/dev/sd{0}1'.format(chr(ord('b')+i))] = t

    return self.conn.run_instances(image_id, instance_type=instance_type,
                                   min_count=min_count,
                                   max_count=max_count,
                                   key_name=key_name,
                                   security_groups=security_groups,
                                   placement=placement,
                                   user_data=user_data,
                                   placement_group=placement_group,block_device_map = map)
```

Details for the boto side are here: https://groups.google.com/forum/?fromgroups=#!topic/boto-users/7igfHM9CChk

**Comment by jstjohn** [comment]
Excellent, thanks for the code!

**Comment by egafni** [comment]
No problem.  I also just wrote a starcluster plugin to install gluster and setup all the ephemeral drives of the hs1 as a 48TB shared mount point across the cluster.  If you'd like to use it come to the #starcuster channel on irc

**Comment by jstjohn** [comment]
I would love to use those plugins. I was planning on writing one to do the 48Tb shared mount point thing actually, and I had previously thought about glusterfs and writing up one to do that. I would be interested in hearing how those two styles of storage compare with compute performance, or do you use them both, for different things maybe? I will hop onto IRC whenever I get some spare time over the next few days, hopefully I will run into you there.

**Comment by egafni** [comment]
Cool, I'm usually idleing in the channel while working (which is most of the time these days).  It'd be nice to have someone else playing with gluster setups as there's lots of configurations to try.  Yesterday I was using it to create a 2TB share on the hi1 SSD instances but decided to move to the hs1 instance today.

**Comment by egafni** [comment]
Sorry i missed you, i'm erik49
