### ISSUE TITLE
node.get_device_map() is not working

### ISSUE THREAD

**Issue by egafni** [jtriley/StarCluster#205]
I've only tested on an m1.large, but its returning an empty dict and /proc/partitions is not empty
# cat /proc/partitions

major minor  #blocks  name

 202        1   10485760 xvda1
 202       17  440366080 xvdb1
 202       33  440366080 xvdc1
 202       49  440366080 xvdd1
 202       65  440366080 xvde1

**Comment by jtriley** [comment]
Interesting, looking into this now. Thanks for reporting!
