### ISSUE TITLE
Cannot change SGE plugin order

### ISSUE THREAD

**Issue by egafni** [jtriley/StarCluster#207]
If i set plugins = myplugin, sge

sge gets installed twice.  My hope was to be able to run my plugin before sge.

**Comment by FinchPowers** [comment]
Have you set in the config "DISABLE_QUEUE = True" ?

**Comment by jtriley** [comment]
@egafni @FinchPowers is right, you most likely need to set disable_queue = True to disable SGE from being configured by default.

**Comment by jtriley** [comment]
Please reopen if setting disable_queue = True doesnt fix the issue...
