### ISSUE TITLE
adding nodes creating repeated entries in ~root/.ssh/known_hosts for master node

### ISSUE THREAD

**Issue by scrappythekangaroo** [jtriley/StarCluster#208]
I've noticed that each time I add a node duplicate master entries are created in known_hosts for root user on master node.

A sample fix below which I've only briefly tested:
https://github.com/scrappythekangaroo/StarCluster/commit/012885190ba347917fd23975b23a5c9c7d15dfcb

**Comment by jtriley** [comment]
@scrappythekangaroo I'll test this out and merge your fix (provided it fixes the issue of course ;). Thanks for reporting!
