### ISSUE TITLE
node.get_partition_map() returns empty dict

### ISSUE THREAD

**Issue by egafni** [jtriley/StarCluster#212]
m.get_partition_map() is returning an empty dict.  You're using fdisk -l but perhaps an easier way to to cat /proc/partitions

m.get_partition_map()
Out[9]: {}

m.ssh.execute('cat /proc/partitions')
Out[10]: 
['major minor  #blocks  name',
 '',
 '202        1   10485760 xvda1',
 '202       17 1073741824 xvdb1',
 '202       33 1073741824 xvdc1',
 '202       80  367001600 xvdf',
 '202      112   41943040 xvdh']

**Comment by jtriley** [comment]
those are not partitions, those are devices (see fdisk -l)

**Comment by jtriley** [comment]
Particularly, you should notice that fdisk -l reports that those devices have no partition table. FYI /proc/partitions displays _both_ partitions and devices so just blindly assuming those values are true partitions is incorrect.

**Comment by jtriley** [comment]
Also, /proc/partitions does not provide the start/end/block count that fdisk does for true partitions. This info is required by the resizevolume command in the case that the original EBS volume has a single partition.
