### ISSUE TITLE
how to integrate slurm in Starcluster

### ISSUE THREAD

**Issue by aaravindanarun** [jtriley/StarCluster#232]
I have good experience knowledge in Slurm Cluster. I am interest to learning how to integrate slurm cluster using STARCLUSTER.

Referred Below links.
https://github.com/jlafon/StarCluster/wiki/Getting-Started-with-SLURM-on-Amazon-EC2 

But, I got the error message

starcluster start mycluster -c starcluster -s 2
StarCluster - (http://web.mit.edu/starcluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

!!! ERROR - Plugin class starcluster.plugins.slurm.Slurm does not exist

Please tell me how to solve this problem.

Herewith enclosed my config file.
###### 
###### 

[cluster starcluster]

KEYNAME = starcluster

CLUSTER_SIZE = 2

CLUSTER_USER = sgeadmin

CLUSTER_SHELL = bash

NODE_IMAGE_ID =  ami-868dcfd4
NODE_INSTANCE_TYPE = t1.micro
DISABLE_QUEUE=True
PLUGINS = createusers, slurm
PERMISSIONS = ssh, http

[plugin slurm]
SETUP_CLASS = starcluster.plugins.slurm.Slurm
COMPUTE_ON_MASTER = True
ADD_USERS = True

[plugin createusers]
SETUP_CLASS = starcluster.plugins.users.CreateUsers
usernames = arvindan, arun, larry

or please share sample config file.

**Comment by jtriley** [comment]
Slurm is not yet supported by StarCluster. Those instructions you linked and the Slurm plugin were created by @jlafon so please file Slurm plugin issues on @jlafon's fork for now. Reading those instructions your first issue is that you're not using @jlafon's fork of StarCluster which is why the plugin cannot be found.

**Comment by aaravindanarun** [comment]
Thanks for reply, Time being i am dropped my plan to integrate slurm on StarCluster.

**Comment by satra** [comment]
@jtriley - any further updates on this?

**Comment by pescobar** [comment]
is there any plan to add slurm integration in starcluster?
