### ISSUE TITLE
Adding Node Failure - exception.InstanceDoesNotExist

### ISSUE THREAD

**Issue by daskinne** [jtriley/StarCluster#234]
Exception when adding nodes, specifically node003. If node003 is added when the cluster is first created, or in an add node request that contains node001 or node002 at the same time it will complete ok. This problem only occurs when node003 is the first node in the add request.

```
an -n 3 cluster_name <- will work ok
```

Error:

```
an -n 2 cluster_name <ok>
an -n 1 cluster_name <fails> ----or----
an -n N cluster_name <fails> 
```

In both cases the instance comes up shortly after the error so this is likely a problem with cluster->wait_for_ssh

```
<type 'exceptions.Exception'>
Traceback (most recent call last):
    starcluster.cluster.add_nodes(numnodes, spot_bid=None)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 888, in add_nodes
    node = self.get_node_by_alias(alias)
  File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 732, in get_node_by_alias
    raise exception.InstanceDoesNotExist(alias, label='node')
starcluster.exception.InstanceDoesNotExist: node 'node003' does not exist
```

```
StarCluster - (http://star.mit.edu/cluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

3/3 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
3/3 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
!!! ERROR - node 'node003' does not exist
```

```
starcluster lc
StarCluster - (http://star.mit.edu/cluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

-----------------------------------------------
cluster_name (security group: @sc-cluster_name)
-----------------------------------------------
Launch time: 2013-03-20 14:34:59
Uptime: 0 days, 00:04:47
Zone: us-east-1d
Keypair: swskey
EBS volumes: N/A
Cluster nodes:
     master running i-27d1d948 ec2-50-19-184-68.compute-1.amazonaws.com
    node001 running i-358d1a5a ec2-54-235-32-239.compute-1.amazonaws.com
    node002 running i-7f8d1a10 ec2-107-22-3-238.compute-1.amazonaws.com
Total nodes: 3
```

```
starcluster lc
StarCluster - (http://star.mit.edu/cluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

-----------------------------------------------
cluster_name (security group: @sc-cluster_name)
-----------------------------------------------
Launch time: 2013-03-20 14:34:59
Uptime: 0 days, 00:04:54
Zone: us-east-1d
Keypair: swskey
EBS volumes: N/A
Cluster nodes:
     master running i-27d1d948 ec2-50-19-184-68.compute-1.amazonaws.com
    node001 running i-358d1a5a ec2-54-235-32-239.compute-1.amazonaws.com
    node002 running i-7f8d1a10 ec2-107-22-3-238.compute-1.amazonaws.com
    node003 running i-68f9490b ec2-54-242-135-98.compute-1.amazonaws.com
Total nodes: 4
```

```
starcluster rn cluster_name node003
StarCluster - (http://star.mit.edu/cluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

>>> Running plugin starcluster.plugins.sge.SGEPlugin
>>> Removing node003 from SGE
!!! ERROR - Error occured while running plugin 'starcluster.plugins.sge.SGEPlugin':
!!! ERROR - remote command 'source /etc/profile && qconf -dconf node003'
!!! ERROR - failed with status 1:
!!! ERROR - can't resolve hostname "node003"
!!! ERROR - can't delete configuration "node003" from list:
!!! ERROR - configuration does not exist
```

**Comment by scrappythekangaroo** [comment]
I've also encountered this problem recently (in v. 0.93.3).  Haven't had a chance to look deeper yet since it's only coming up intermittently (latest occurrence was with node005).   The temporary fix I have at the moment is to manually terminate the node from the AWS console and try adding again with starcluster.    Since none of the starcluster plugins have been run yet for the failed add node operation this doesn't cause any problems, but it does mean that you lose one hour of paid uptime for that node.

**Comment by scrappythekangaroo** [comment]
I also got something a little bit different, but appears to be related

> > > Launching node(s): node006
> > > Waiting for node(s) to come up... (updating every 30s)
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
> > > !!! ERROR - instance 'i-c87c08a2' does not exist

This means the problem may have wider implications than just cluster->wait_for_ssh.  Maybe there is some latency on the AWS side or a bug in boto.... I'm not familiar enough with this part of the code.

I can confirm that this instance did appear in the AWS console though instance name field was left blank, thus the bug.

**Comment by scrappythekangaroo** [comment]
Should also add, instead of doing terminate from the Amazon console, you can probably just run  

starcluster addnode -x -a mynode1,mynode2,mynode3 mycluster

as shown in the cli help.

**Comment by daskinne** [comment]
@scrappythekangaroo 
I have had a lot of problems with 93.3

I suggest you fork https://github.com/datacratic/StarCluster
and join in testing this with me if you are able.

**Comment by scrappythekangaroo** [comment]
thanks @daskinne I have a fork of 0.9999 which we've been testing so I can already appreciate the many improvements. 

I've also been following  https://github.com/datacratic/StarCluster though have not made a fork of this repos.  Would be happy to join in testing when I have the chance.

**Comment by pparsonsesp** [comment]
I've had this issue. I believe it's in wait_for_active_instances

The code checks to see whether nodes is length 0 before waiting which isn't the case when adding nodes to an existing cluster

 if len(nodes) == 0:
            s = self.get_spinner("Waiting for instances to activate...")
