### ISSUE TITLE
Documentation needs to mention that environment variables can override config file.

### ISSUE THREAD

**Issue by dshafer** [jtriley/StarCluster#244]
I set up starcluster for a personal project using the provided walkthroughs, and have had a great experience using it so far.  However, I was surprised to find that my running instances showed up under my employer's AWS console instead of my personal account console.  AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, and AWS_USER_ID in ~starcluster/config are all configured for my personal account.  I used "starcluster createkey" to instantiate my EC2 keypair after setting the config file values for my personal account.

After much investigation, my suspicion is that this happened because I happen to have these values defined as environment variables for an unrelated work project that uses S3 (populated with the corresponding values for my work account instead of personal account). The generated EC2 keypair was uploaded to my work account instead of my personal account.

While this seems like reasonable behavior, I cannot find it documented anywhere.  At the least, the quick-start guide should note that this behavior exists.

Ideally, it might be good to have some sort of scare text printed when environment vars are being used to override config file values when starcluster is doing things that can result in charges to the AWS account.

**Comment by jtriley** [comment]
@dshafer Great point and sorry for the confusion! I'm adding a note to the docs now and will also add a warning to the code when these variables are active.
