### ISSUE TITLE
TaskRecord key 'started' not set

### ISSUE THREAD

**Issue by revoltek** [jtriley/StarCluster#249]
The TaskRecord key 'started' is set only when the job is completed and not when it actually starts.

Here for example a job is running but I cannot recover when it started:

```
c.db_query({'completed' : None},['msg_id','started','engine_uuid'])
[{u'engine_uuid': u'46607547-68e2-478f-bbcf-21d462b54ae9',
u'msg_id': u'57480a18-91c3-44fc-b774-0b0ab1659b4f',
u'started': None}]
```

**Comment by jtriley** [comment]
I think you meant to post this to the https://github.com/ipython/ipython issue list so I'm going to close this for now. If this is an issue with the IPython plugin for StarCluster please repoen and provide more details. Thanks!
