### ISSUE TITLE
Auto Scaling not working when disabling job execution on master node

### ISSUE THREAD

**Issue by aaravindanarun** [jtriley/StarCluster#256]
Built own customized AMI on CentOS 6.3 64 bit, I tried enabled load balancer option with disabling job execution on Master Node.

> > > Loading full job history
> > > Execution hosts: 1
> > > Queued jobs: 10
> > > Oldest queued job: 2013-06-07 05:53:18
> > > Avg job duration: 300 secs
> > > Avg job wait time: 165 secs
> > > Last cluster modification time: 2013-06-07 05:54:32
> > > A job has been waiting for 796 sec, longer than max 300
> > > Sleeping...(looping again in 10 secs)
> > > 
> > > Loading full job history
> > > Execution hosts: 1
> > > Queued jobs: 10
> > > Oldest queued job: 2013-06-07 05:53:18
> > > Avg job duration: 300 secs
> > > Avg job wait time: 165 secs
> > > Last cluster modification time: 2013-06-07 05:54:32
> > > A job has been waiting for 810 sec, longer than max 300
> > > Sleeping...(looping again in 10 secs)
> > > 
> > > Loading full job history
> > > Execution hosts: 1
> > > Queued jobs: 19
> > > Oldest queued job: 2013-06-07 05:53:18
> > > Avg job duration: 300 secs
> > > Avg job wait time: 165 secs
> > > Last cluster modification time: 2013-06-07 05:54:32
> > > A job has been waiting for 822 sec, longer than max 300
> > > Sleeping...(looping again in 10 secs)

**Comment by jtriley** [comment]
@aaravindanarun _Please_ post the entire command you ran and not just snippets of the output. Also I'm not really sure what the actual problem here is given that there's not enough details. Are you sure you disabled master because it looks like you have 1 execution host in the cluster. How many nodes are in the cluster? How many jobs do you have queued? What is the expected behavior? More details here would help. Thanks!

**Comment by aaravindanarun** [comment]
Ignore Master node from exection node on Starcluster tools - load balance.

```
 Reference Link: https://github.com/jtriley/StarCluster/pull/216/files
 https://github.com/jtriley/StarCluster/pull/216
 https://github.com/jtriley/StarCluster/commit/f90d9f262a6d66ba5002f43b191df57a298b92e3
 https://github.com/jtriley/StarCluster/commit/6a62e908bd08b2dae86209ffceda3c0725933a49
 https://github.com/jtriley/StarCluster/commit/c8d98834822d17ffc38eb761dd29699db3edd299
 https://github.com/jtriley/StarCluster/commit/40b97493c58d183642e440f54c450b3e2544c6d8
 https://github.com/jtriley/StarCluster/commit/b938518bc89d58feda6e21e673307b8dc2ce18a3
```
