### ISSUE TITLE
Problem to stop/terminate running instance using starcluster tool

### ISSUE THREAD

**Issue by aaravindanarun** [jtriley/StarCluster#259]
1.starcluster stop imagehost

StarCluster - (http://web.mit.edu/starcluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

Stop cluster imagehost (y/n)? y

> > > Running plugin sge
> > > Detaching volume vol-d618f5de from master
> > > !!! ERROR - IncorrectInstanceState: Unable to detach volume 'vol-d618f5de' with Marketplace codes from instance 'i-d9eb1c8f' as the instance is not in the 'stopped' state.

**Comment by jtriley** [comment]
Duplicate of #238 - looking at #238 now
