### ISSUE TITLE
Failed to remove security group at termination

### ISSUE THREAD

**Issue by syoyo** [jtriley/StarCluster#270]
In my EC2-VPC and Tokyo region configuration, every time I encounter following problem when terminating cluster.

```
$ starcluster terminate smallcluster
...
>>> Terminating node: master (i-d4e2add6)
>>> Terminating node: node001 (i-dae2add8)
>>> Waiting for cluster to terminate... 
>>> Removing @sc-smallcluster security group
!!! ERROR - Failed to load cluster settings!
!!! ERROR - Use -f to forcefully terminate the cluster
!!! ERROR - DependencyViolation: resource sg-4f937620 has a dependent object
```

After waiting some time(to ensure instances fully terminate), then force-terminate cluster(`terminate -f smallcluster`) solves this error, so my humble guess is adding some delay for the deletion of security group after instance termination.

FYI, this issue seems _NOT_ related to 'default' VPC issue. 265

**Comment by jtriley** [comment]
@syoyo Actually this is the exact same bug as #265. Need to apply the same fix in Cluster.terminate_cluster. Also I have a different (hopefully more robust) fix for #265 that I'm working on.

**Comment by jtriley** [comment]
@syoyo Since you have a VPC-only account in that region can you please give me the output of:

```
$ starcluster shell
[1]>print ec2.conn.describe_account_attributes('supported-platforms')[0].attribute_values
[2]>print ec2.conn.describe_account_attributes('default-vpc')[0].attribute_values[0]
```

**Comment by syoyo** [comment]
Sure, here it is

```
In [1]: print ec2.conn.describe_account_attributes('supported-platforms')[0].attribute_values
[u'VPC']

In [2]: print ec2.conn.describe_account_attributes('default-vpc')[0].attribute_values[0]
vpc-ab35ecc3
```

**Comment by jtriley** [comment]
@syoyo Perfect, thank you!

**Comment by syoyo** [comment]
Unfortunately I still get same error...

```
$ starcluster terminate smallcluster
Terminate EBS cluster smallcluster (y/n)? y
>>> Running plugin starcluster.plugins.sge.SGEPlugin
>>> Running plugin starcluster.clustersetup.DefaultClusterSetup
>>> Terminating node: master (i-e21a53e0)
>>> Terminating node: node001 (i-e01a53e2)
>>> Waiting for cluster to terminate... 
>>> Removing @sc-smallcluster security group
!!! ERROR - Failed to load cluster settings!
!!! ERROR - Use -f to forcefully terminate the cluster
!!! ERROR - DependencyViolation: resource sg-13e5007c has a dependent object
```

**Comment by jtriley** [comment]
@syoyo Hmm, OK can you please try running `$ starcluster listinstances` immediately after you get that error and post the output? I want to at least verify that the instances have terminated when this error occurs. If that's the case we may just need to retry deleting the group in a loop until it's successful...

**Comment by syoyo** [comment]
@jtriley, here's output

```
$ starcluster terminate smallcluster
...
>>> Terminating node: master (i-1cdf961e)
>>> Terminating node: node001 (i-22df9620)
>>> Waiting for cluster to terminate... 
>>> Removing @sc-smallcluster security group
!!! ERROR - Failed to load cluster settings!
!!! ERROR - Use -f to forcefully terminate the cluster
!!! ERROR - DependencyViolation: resource sg-71ed081e has a dependent object

$ strarcluster listinstances
...
>>> No instances found

$ starcluster listclusters
...
-----------------------------------------------
smallcluster (security group: @sc-smallcluster)
-----------------------------------------------
Launch time: N/A
Uptime: N/A
Zone: N/A
Keypair: N/A
EBS volumes: N/A
Cluster nodes: N/A
```

**Comment by jtriley** [comment]
@syoyo Thanks for all your testing this is very helpful. OK so it seems that the instances _are_ terminated. @adgaudio also reported the exact same issue in #21 although I dont believe he was using the instance.group-name filter in Cluster.is_cluster_terminated like the current develop branch does. I've asked him to test if he still has the problem as well after pulling/making that change.

Assuming he still has the issue I think unfortunately all we can do is keep retrying to delete the security group until it succeeds. I'm not aware of any other condition that would prevent the group from being deleted other than all instances being terminated and it seems a short period of time is all that's needed for it to later be deleted anyway.

**Comment by jtriley** [comment]
@syoyo OK, that _should_ fix it. Let me know if it doesn't.

**Comment by syoyo** [comment]
@jtriley Cool! Confirmed now it works. Thanks for the fix!
