### ISSUE TITLE
Issues Launching in us-west-1

### ISSUE THREAD

**Issue by bmccann** [jtriley/StarCluster#271]
Following the quickstart tutorial, I am able to get a cluster up and running. However, I would like to specify my default region as us-west-1, and this appears to preclude starting a cluster. 

I can successfully create a keypair in the region, but trying to start gives the following error:

```
$ starcluster start mycluster
StarCluster - (http://web.mit.edu/starcluster) (v. 0.93.3)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

>>> Using default cluster template: smallcluster
>>> Validating cluster template settings...
>>> Cluster template settings are valid
>>> Starting cluster...
>>> Launching a 2-node cluster...
>>> Creating security group @sc-mycluster...
!!! ERROR - InvalidParameterValue: Invalid security group description. Valid descriptions are strings less than 256 characters from the following set:  a-zA-Z0-9. _-:/()#,@[]+=&;{}!$*
```

In the config, the only lines I changed between a successful start and a failed start are:

```
AWS_REGION_NAME = us-west-1
AWS_REGION_HOST = ec2.us-west-1.amazonaws.com
...
NODE_IMAGE_ID = ami-e15c02a4 (tried with other imaged given by starcluster lp)
```

**Comment by izharw** [comment]
I had the same issue with the stable version (0.93.3). Using the
development version from the git repository solved it...

**Comment by bmccann** [comment]
Thank you for the quick response. Reinstalling from git rather than by easy_install Starcluster appears to have fixed the issue.

**Comment by jtriley** [comment]
@bmccann @izharw StarCluster 0.94 has been released which should fix this issue.

**Comment by scollis** [comment]
I know this is closed.. just letting you all know the Anaconda Python install on EC2 is also broken.. fixed by wget https://pypi.python.org/packages/source/S/StarCluster/StarCluster-0.95.6.tar.gz
