### ISSUE TITLE
Unable to Specify UDP Port Ranges Using Config File

### ISSUE THREAD

**Issue by huwdjones** [jtriley/StarCluster#279]
Hi there,

I think a few other people have noticed this. Basically when trying to set up a UDP range within an AWS security group within the StarCluster config file on creating the cluster only TCP ranges are being set. This is an issue when wanting to create an NFS share with another machine that is not part of the cluster.

Kind regards

Huw Jones

**Comment by jtriley** [comment]
@huwdjones Can you please paste one of the [permission] sections from your config that's not being applied when creating a cluster? Thanks.

**Comment by huwdjones** [comment]
Hi

I have since amended the sections however it was something like:

# list of permissions (or firewall rules) to apply to the cluster's security

# group (OPTIONAL).

PERMISSIONS = http, udp

############################################

## Configuring Security Group Permissions

############################################

# Sections starting with "permission" define security group rules to

# automatically apply to newly created clusters. PROTOCOL in the following

# examples can be can be: tcp, udp, or icmp. CIDR_IP defaults to 0.0.0.0/0 or

# "open to the # world"

# open port 80 on the cluster to the world

[permission http]
PROTOCOL = tcp
FROM_PORT = 80
TO_PORT = 80

# open udp on the cluster to the world

[permission udp]
PROTOCOL = udp
FROM_PORT = 2049
TO_PORT = 2049

# open port 80 on the cluster to an ip range using CIDR_IP

# [permission http]

# PROTOCOL = tcp

# FROM_PORT = 80

# TO_PORT = 80

# CIDR_IP = 18.0.0.0/8

# restrict ssh access to a single ip address (<your_ip>)

# [permission ssh]

# PROTOCOL = tcp

# FROM_PORT = 22

# TO_PORT = 22

# CIDR_IP = <your_ip>/32

Apologies that I no longer have the exact copy. I can try and recreate the issue if you like?

As an aside I am also trying to connect to the cluster through a python script. I can see a lot of documentation online about how to create a cluster from within a python script using StarCluster modules however I can't find any examples where the cluster already exists and the script enters the cluster name or id to connect to its master node via SSH. I don't suppose you have an example do you?

Much appreciated

Huw Jones

**Comment by jtriley** [comment]
@huwdjones Looking into this closely it turns out there's an error in the config template docs. I'm working on a fix but for now now you can get around this issue by replacing `PROTOCOL` with `IP_PROTOCOL`.

**Comment by jtriley** [comment]
@huwdjones Also, concerning using StarCluster from a Python script: I need to write some (better) developer docs that showcase how to use StarCluster from Python but for now you can accomplish what you're wanting with:

```
from starcluster import config
from starcluster import cluster
cfg = config.StarClusterConfig().load()
cm = cluster.ClusterManager(cfg)
cl = cm.get_cluster('MYCLUSTER')
```

Then you can iterate through nodes like so:

```
for node in cl.nodes:
    print node.ssh.execute("hostname")
```

**Comment by jtriley** [comment]
@huwdjones Also, if you want just the master:

```
print cl.master_node.ssh.execute("hostname")
```

Hope that helps...

**Comment by huwdjones** [comment]
Hi Justin that's great thanks I'll try it out and let you know.

As an aside I am also trying to connect to the cluster through a python script. I can see a lot of documentation online about how to create a cluster from within a python script using StarCluster modules however I can't find any examples where the cluster already exists and the script enters the cluster name or id to connect to its master node via SSH. I don't suppose you have an example do you?

Kind regards

Huw

**Comment by huwdjones** [comment]
That's great - exactly what I was looking for.

Many thanks

Huw Jones
