### ISSUE TITLE
Sometimes instances alias definition fails

### ISSUE THREAD

**Issue by FinchPowers** [jtriley/StarCluster#287]
Frequency: Very low

Loadbalancer running. Trying to add a node. For some reason the created node name remains "undefined" and StarCluster raises "InstanceDoesNotExist". Here is the execution trace.

Last cluster modification time: 2013-08-28 02:51:20
**\* WARNING - Adding 1 nodes at 2013-08-28 13:13:35.893596

> > > Launching node(s): node001
> > > Still waiting for instances [u'sir-23e25a34']
> > > SpotInstanceRequest:sir-23e25a34
> > > Waiting for node(s) to come up... (updating every 30s)
> > > Waiting for open spot requests to become active...
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Waiting for all nodes to be in a 'running' state...
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Waiting for SSH to come up on all nodes...
> > > 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%
> > > Waiting for cluster to come up took 3.033 mins
> > > Traceback (most recent call last):
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/balancers/sge/**init**.py", line 759, in _eval_add_node
> > >     placement_group=self._placement_group)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 993, in add_nodes
> > >     node = self.get_node_by_alias(alias)
> > >   File "/usr/local/lib/python2.7/dist-packages/StarCluster-0.9999-py2.7.egg/starcluster/cluster.py", line 800, in get_node_by_alias
> > >     raise exception.InstanceDoesNotExist(alias, label='node')
> > > InstanceDoesNotExist: node 'node001' does not exist
> > > !!! ERROR - Failed to add new host

I don't think there is any error StarCluster wise since it occurs very rarely. I think it's on EC2. Still, StarCluster should handle it.

**Comment by scrappythekangaroo** [comment]
hi @FinchPowers is this related problem as reported in #234 & #268 ?   It's supposedly fixed, but maybe not?

**Comment by FinchPowers** [comment]
Thanks @scrappythekangaroo 
But I don't think so. #268 is related to instances propagation which seems to be fixed indeed. In my case the instance is created but the tags are not properly defined and hence the tag alias having a value of "node001" doesn't exist. Also, when I look at the EC2 console the instance name is "undefined". So both tags and name are not defined.

**Comment by scrappythekangaroo** [comment]
Is it possibly exceeding the max_retries in _wait_for_propagation?  I guess it would have shown up in the logs.

**Comment by FinchPowers** [comment]
Might be caused by the fact that I'm not on the lastest version. I'll update and see how it goes.
