### ISSUE TITLE
StarCluster crash when instances boot fails on "State Transition Reason: Server.InternalError: Internal error on launch"

### ISSUE THREAD

**Issue by FinchPowers** [jtriley/StarCluster#288]
Occurences: Very low

Just launched a couple of instances. One of them did not boot properly. The interface shows "State Transition Reason: Server.InternalError: Internal error on launch" so it's definitely on EC2 side.

However SC crashed.

**Comment by jtriley** [comment]
@FinchPowers I believe this is the same problem a in gh-329 which basically boils down to an issue with StarCluster's custom block device maps and m1.small + 32bit AMI. I'm fairly confident I've fixed this so I'm going to close this issue. Please re-open if you run into the issue again.
