### ISSUE TITLE
Passing along user-data script to addnode

### ISSUE THREAD

**Issue by ro6ert** [jtriley/StarCluster#296]
Hello Jtriley,

We are using the -U argument to the startcluster start command to pass in a script which registers the headnode and user nodes with our chef-server.

When we run the "addnode" command there does not appear to be a -U option. Is there a way to pass user data to new nodes?

-Rob

**Comment by jtriley** [comment]
@ro6ert The addnode command does not have a userdata option yet, however, it _should_ (IIRC) use the original user-data used to launch the cluster. Have you tried running the addnode command and verifying whether the user data scripts execute?

**Comment by ro6ert** [comment]
@jtriley We are using starcluster with Eucalyptus. Eucalyptus does not implement the describeinstanceattribute method yet so boto cannot fetch the userdata from the head node. We found a work around in the boto code by spoofing the userdata file. We are using knife instead of the userdata file to make contact with the chef server.
