### ISSUE TITLE
tmux "control" of the nodes

### ISSUE THREAD

**Issue by npinto** [jtriley/StarCluster#3]
It would be nice to have a "tmux control center" of all the nodes started.

Thanks!

-- Nicolas

**Comment by jtriley** [comment]
this will be added as a plugin

**Comment by jtriley** [comment]
work in progress in feature branch: https://github.com/jtriley/StarCluster/tree/feature/tmux-plugin

**Comment by npinto** [comment]
Awesome! Thanks a ton Justin!

**Comment by jtriley** [comment]
btw, no need to append ^M character to commands sent via send-keys, just follow up with another send-keys command that simply sends "Enter". see the new tmux plugin: https://github.com/jtriley/StarCluster/blob/feature/tmux-plugin/starcluster/plugins/tmux.py
