### ISSUE TITLE
Node.ec2 object does not hold the aws_access_key_id and aws_secret_access_key when access in a plugin

### ISSUE THREAD

**Issue by nkrumm** [jtriley/StarCluster#302]
In the boto.py plugin, it seems possible to grab the AWS credentials via the `master` object, which I believe is a `Node` object, via the `master.ec2` property. However, the `master.ec2.aws_access_key_id` and `master.ec2.aws_secret_access_key` both return None in the context of a plugin. Instead, these can be accessed via `master.ec2._conn.aws_access_key_id` etc.

I think this is the case because in `starcluster/Node.py`, lines 84-85:

``` python
self.ec2 = awsutils.EasyEC2(None, None)
self.ec2._conn = instance.connection
```

the EasyEC2 is not really created, and `instance.connection` is "injected" instead. 

This is not a huge deal (just use `master.ec2._conn`) but I think it is breaking the boto plugin. Could be fixed by manually copying over the two keys, or by correctly instantiating the EasyEC2 object. Thanks!

**Comment by jtriley** [comment]
@nkrumm Confirmed, thanks for reporting. Fix coming....
