### ISSUE TITLE
PackageInstaller fails because apt-get update is never run.

### ISSUE THREAD

**Issue by jharlap** [jtriley/StarCluster#314]
If you use the bundled PackageInstaller plugin with a package that has been updated since the AMI was created then it fails because at no point is `apt-get update` ever run. I'd suggest either making it part of node.apt_install or at least making the PackageInstaller explicitly call `node.apt_command('update')` - although I believe making apt_install implicitly call apt-get update automatically is a safer approach.

Unfortunately I didn't take note of exactly which package is an example that causes the failure, but it's one of the following: libnetcdf-dev, libhdf5-serial-dev, libnetpbm10-dev, fftw-dev, libgsl0-dev, libgetopt-tabular-perl, libxext-dev, imagemagick, libtext-format-perl, freeglut3-dev

**Comment by jtriley** [comment]
Thanks for reporting!
