### ISSUE TITLE
iso file mounting documentation

### ISSUE THREAD

**Issue by Gurado** [jtriley/StarCluster#320]
I believe the documentation on the website for mounting the iso is missing a bit:

http://star.mit.edu/cluster/download_amis.html

$ mount -o loop /path/to/starcluster-base-ubuntu-10.04-x86.iso /mnt/

should probably be 

$ mount -o loop /path/to/starcluster-base-ubuntu-10.04-x86.iso /mnt/starcluster-base-ubuntu-10.04-x86/

At least thats the way it worked for me.

Also you may want to add a note indicating that the host environment probably needs to be compatible with the image. I had problems with chroot on a debian 32-bit box trying to mount the 64-bit starcluster-base-ubuntu-11.10-x86_64.iso.gz image, which gave me the following error message:
"chroot: failed to run command `/bin/bash`: Exec format error".

Switching to a 64-bit host system worked nicely.

Cheers!

**Comment by jtriley** [comment]
Fixed now, thanks!!
