### ISSUE TITLE
Issue with Server.InternalError: Internal error on launch

### ISSUE THREAD

**Issue by jtriley** [jtriley/StarCluster#329]
From https://gist.github.com/cb372/6b820c1041a871611c21

Hi Justin, thanks for the support!

Following the Quick Start to the letter, I get as far as starting a 2-node cluster ('starcluster start mycluster'). 
Both EC2 machines are created, but then fail to boot up. 
In the EC2 console, their state goes straight from Pending to Terminated. 
StarCluster gives the following error for each machine.

!!! ERROR - i-907950eb (terminated) Server.InternalError: Internal error
!!! ERROR - on launch

Unfortunately I can't find any more useful logs. Because the machines do not boot, there is no System Log to view in the EC2 console.

I wish I could provide a more useful bug report. Have you ever heard of something similar to this?

**Comment by jtriley** [comment]
@cb372 You're using 0.94.2 correct? Also, what region and AMI are you using?

**Comment by cb372** [comment]
Yes, 0.94.2. I left the region and AMI as their default values, so I'm using us-east1 and ami-7c5c3915 (m1.small)

By the way I just tried the same steps on my machine at work and I get the same error.

**Comment by jtriley** [comment]
@cb372 OK I just tried with the 32bit AMIs and hit the same issue. I'm looking into this now but in the meantime please try the 64bit 12.04 AMI: ami-765b3e1f

In general you can list all available StarCluster AMIs in a given region using:

```
$ starcluster -r us-east-1 listpublic
```

I'm going to set the 64bit AMIs as the default in the config template given that they're more commonly used these days for all instance types.

**Comment by jtriley** [comment]
OK so this definitely has to do with StarCluster's custom block device mappings but oddly enough it's _only_ an issue for 32bit m1.small instances. All other instance types that support 32bit (ie t1.micro, m1.medium, c1.medium) work just fine with the 32bit StarCluster AMIs. I'll likely put a special case in to skip the custom block device map if using m1.small with a 32bit AMI.
