### ISSUE TITLE
do not launch the master instance using spot instances by default

### ISSUE THREAD

**Issue by jtriley** [jtriley/StarCluster#33]
When using -b option to launch a cluster with size >1 do not launch the master using a spot instance request; use a flat-rate request instead. If cluster size == 1 then this is OK given that it's only a single machine and no other machines have NFS shares mounted, etc. Probably need to also add an option to force master to be spot... (--spot-master?)

**Comment by jtriley** [comment]
implemented this with "force master to be spot" option being --force-spot-master

**Comment by omus** [comment]
I don't think that having clusters with a size of 1 should automatically start as a spot instance when using the -b option. I use the loadbalancer to automatically add nodes to my cluster and I would prefer my master node to start as an on-demand instance for stability. Alternatively if this default behaviour is to stay an option such as --force-demand-master should be added.

I'll also note that the documentation at http://web.mit.edu/star/cluster/about.html states "The master node is launched as an on-demand instance by default for stability".

**Comment by jtriley** [comment]
I agree. I originally did this to avoid passing --force-spot-master when developing with 1-node clusters. Not a good excuse but that was the rationale at the time. I completely overlooked the fact that this breaks the use case of a single on-demand master with spot nodes dynamically added/removed using the loadbalancer. Furthermore having a spot master for development isn't really necessary anymore given that on-demand micro instances are so cheap it's easier to just use them for testing at a low price.

I'll make the change soon and it'll be included in the next release.

**Comment by omus** [comment]
Awesome, thanks!

**Comment by jtriley** [comment]
@omus all set in develop branch: 3b3c2661fff29cd54cfb197a0514178cc6691b37

**Comment by yairmov** [comment]
How does the SPOT_BID parameter in the config file affects this? I have a config file where the SPOT_BID is uncommented, and CLUSTER_SIZE = 1 just for the use case described above. The idea is to add spot nodes when needed. But the master node is launched as spot.
Should I comment the SPOT_BID parameter, and add a -b flag when adding worker nodes?

**Comment by jtriley** [comment]
@yairmov The master node will always be launched as a flat-rate instance unless you set FORCE_SPOT_MASTER=True in your config OR use --force-spot-master command line option to 'start' command. The SPOT_BID config setting simply declares what the default spot bid will be when requesting spot nodes. You can always override your SPOT_BID config setting using the '-b' flag when adding nodes.

**Comment by jtriley** [comment]
@yairmov Keep in mind that if you specify SPOT_BID in your cluster config then any cluster started with that config will always use spot instances.

**Comment by yairmov** [comment]
Thanks for the info. From what I understand from your comment the master is always launched as a flat-rate (unless specifically forced not to). I might be doing something wrong without realizing it, but when I run a cluster with 1 node (master only) and the config file has the SPOT_BID flag uncommented, the master is run as a spot node. As a work around I commented out SPOT_BID, launched a single node cluster and then added more nodes using the -b flag.

Thanks again
