### ISSUE TITLE
The put command doesn't always match every pushd with a popd

### ISSUE THREAD

**Issue by liffiton** [jtriley/StarCluster#331]
<code>starcluster put</code> does not always call <code>_send_popd</code> once for every <code>_send_pushd</code>, and it can result in silently corrupted directory structures at the destination (i.e., incorrect nesting).  I've seen two related issues:
1. <code>starcluster put clustername srcdir srcfile dest</code> can put srcfile inside srcdir if srcdir has nested directories.  This is because the <code>_send_popd</code> call on [line 194 of scp.py](https://github.com/jtriley/StarCluster/blob/develop/starcluster/sshutils/scp.py?source=cc#L194) has assumed the SCP session is only one directory deep at that point.
2. If one directory name is contained entirely within another (e.g. "dirname" and "dirname2"), the commonprefix condition on [line 187](https://github.com/jtriley/StarCluster/blob/develop/starcluster/sshutils/scp.py?source=cc#L187) can be spuriously triggered, skipping a needed _send_popd, and resulting in the later directories all being placed at least one directory deeper than they should be.  This depends on the order in which the folders are produced by os.walk(), so it will not always be triggered.

The first issue is triggered consistenly by:

```
mkdir srcdir
mkdir srcdir/another
touch srcfile
starcluster put cluster srcdir srcfile .
```

The second one may be triggered by the following, but os.walk() might return the directories in an order that avoids the bug.  The more "a?" folders there are, the better the chances one will be returned after "a" to trigger the bug.

```
mkdir srcdir
mkdir srcdir/a
mkdir srcdir/a2
mkdir srcdir/a3
mkdir srcdir/a4
mkdir srcdir/a5
starcluster put cluster srcdir .
```

The easy workaround is simply to use tar and send a single archive to preserve structures correctly, which is more efficient anyway, so it's not a huge problem.

**Comment by jtriley** [comment]
@liffiton Thanks reporting and providing the steps to reproduce this issue. I was able to reproduce both cases. This code originally came from https://github.com/jbardin/scp.py before it was packaged nicely on PyPI. Now that it's on PyPI I'm going to pull this module and use http://pypi.python.org/pypi/scp as a dependency instead. If the issue still exists we'll report this issue upstream.

**Comment by jtriley** [comment]
@liffiton Update: I've contributed all StarCluster improvements to scp.py back to @jbardin's codebase (https://github.com/jbardin/scp.py) and also fixed this bug along the way. I'm now in the process of removing StarCluster's scp module and declaring http://pypi.python.org/pypi/scp as a StarCluster dependency. I'll close this once that work has been merged. Thanks!!
