### ISSUE TITLE
ebsimage fails when converting instance-store instance

### ISSUE THREAD

**Issue by jbarefoot** [jtriley/StarCluster#334]
I was using an image provided by the Anaconda project and attempting to convert it to ebs.  The anaconda image I was using is ami-a4d64194--confirmed starcluster could launch it fine in a cluster config.

The script hangs after attaching the new EBS volume (see below).  Checking in the AWS console, the volume shows as attached successfully.  Looking at the code, perhaps it is getting some unexpected status value back from the vol.update() call.

Anyway I'll probably just use a stock EBS starcluster image and install latest anaconda on it instead....

```
>>> Removing private data...
>>> Cleaning up SSH host keys
>>> Cleaning up /var/log
>>> Cleaning out /root
>>> Cleaning up /tmp
>>> Creating new EBS-backed image from instance-store instance
>>> Creating new root volume...
>>> Creating 15GB volume in zone us-west-2c
>>> Created new volume: vol-f73a55a1
>>> Attaching volume vol-f73a55a1 to instance i-ddb2a1e9 on /dev/sdz
```

**Comment by jtriley** [comment]
@jbarefoot  Thanks for reporting. Looking into this now.

**Comment by jtriley** [comment]
@jbarefoot I just tried this with anaconda's latest (that I could find anyway) instance-store ami: `ami-39298750`. I was able to successfully create an AMI using the `ebsimage` command:

```
$ starcluster listinstances
id: i-babe41c6
ami: ami-39298750
```

```
$ starcluster ebsimage i-babe41c6 anaconda-amazon-ami-starcluster
>>> Removing private data...
>>> Cleaning up SSH host keys
>>> Cleaning up /var/log
>>> Cleaning out /root
>>> Cleaning up /tmp
>>> Creating new EBS-backed image from instance-store instance
>>> Creating new root volume...
>>> Creating 15GB volume in zone us-east-1a
>>> Created new volume: vol-1748f05a
>>> Attaching volume vol-1748f05a to instance i-babe41c6 on /dev/sdz
>>> Mounting /dev/sdz on /ebs
>>> Configuring /etc/fstab
>>> Syncing root filesystem to new volume (vol-1748f05a)
>>> Unmounting /dev/sdz from /ebs
>>> Detaching volume /dev/sdz from /ebs
>>> Creating snapshot of volume: vol-1748f05a
>>> Waiting for snapshot to complete: snap-660af27c
snap-660af27c: |||||||||||||||||||||||||||||||||||||||||||||100% Time: 00:02:13
>>> New snapshot created: snap-660af27c
>>> Removing generated volume vol-1748f05a
>>> Creating root block device map using snapshot snap-660af27c
>>> Registering new image...
>>> create_image took 5.428 mins
```

I think the issue here is that in the background StarCluster is formatting the device before it moves on and displays the next info message so it appears stuck but it's actually doing something.

I'll fix this by adding an info message for the formatting step. After that if you still have the issue please reopen.

**Comment by jbarefoot** [comment]
Great thanks!  It could be that I just didn't wait long enough, I gave it a
good 10 mins but I guess it could take longer.  I ended up installing a few
things on a default star cluster image and then did an ebsimage on that
instead which worked fine for me.

**Comment by jtriley** [comment]
@jbarefoot Awesome, glad to hear you got things working. The fix for this improves the user experience for the next person that gives this a shot so thanks for reporting!
