### ISSUE TITLE
loadbalance -K crashes if master node outlives the "kill window"

### ISSUE THREAD

**Issue by liffiton** [jtriley/StarCluster#339]
Specifically, I believe that loadbalance -K crashes if:
- the SGE plugin is configured with `MASTER_IS_EXEC_HOST = False`, and
- it takes so long to kill all of the worker nodes that the master node's "time-past-the-hour" wraps around to start at 0.

E.g.:
- Cluster started at 12:00
- loadbalance -K
- Cluster jobs completed at 12:30
- loadbalance begins killing worker nodes at 12:45
- loadbalance finishes killing worker nodes at 13:02
- [_should_remove(self._cluster.master_node)](https://github.com/jtriley/StarCluster/blob/master/starcluster/balancers/sge/__init__.py#L742) returns False, because master node has lived into a new hour, and the cluster is not terminated.

At this point, the next time loadbalance checks the cluster, it crashes with:

```
>>> Loading full job history
Execution hosts: 0
Queued jobs: 0
Avg job duration: 3830 secs
Avg job wait time: 4847 secs
Last cluster modification time: 2013-11-27 01:59:12
>>> Not adding nodes: no queued jobs...
>>> Cluster was modified less than 180 seconds ago
>>> Waiting for cluster to stabilize...
!!! ERROR - Unhandled exception occured
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/starcluster/cli.py", line 274, in main
    sc.execute(args)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/commands/loadbalance.py", line 115, in execute
    lb.run(cluster)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/balancers/sge/__init__.py", line 616, in run
    self.stat.write_stats_to_csv(self.stats_file)
  File "/usr/local/lib/python2.7/dist-packages/starcluster/balancers/sge/__init__.py", line 348, in write_stats_to_csv
    bits = self.get_all_stats()
  File "/usr/local/lib/python2.7/dist-packages/starcluster/balancers/sge/__init__.py", line 338, in get_all_stats
    load_sum = float(reduce(self._add, arr))
TypeError: reduce() of empty sequence with no initial value

!!! ERROR - Oops! Looks like you've found a bug in StarCluster
```

This will be triggered any time the master node is the only node running and it is not an 'exec host' as far as SGE is concerned.  So it is very easy to test:
- Start a cluster w/ one node (the master node only) and `MASTER_IS_EXEC_HOST = False`
- Run loadbalance -K on the cluster

It should be simple to fix, too.  I'll work on a pull request now.

**Comment by jtriley** [comment]
@liffiton Should note this only happens when you're using `--dump-stats` or `--plot-stats`. Thanks for reporting!
