### ISSUE TITLE
amazon attaches ebs vols to alternate device on HVM instances

### ISSUE THREAD

**Issue by jtriley** [jtriley/StarCluster#34]
starcluster attaches EBS volumes to /dev/sd\* and expects the device to mountable via the /dev/sd\* address. With HVM instances the EBS volume devices show up as /dev/xvd\* instead. Need to also check for /dev/xvd\* whenever /dev/sd\* doesn't exist.

**Comment by jtriley** [comment]
actually this isn't true, I assumed this was the case just simply looking at a user's bug report on the mailing list:

http://mailman.mit.edu/pipermail/starcluster/2011-July/000752.html

Upon further investigation it turns out /dev/xvd\* is a symlink to /dev/sd*. The issue experienced is most likely related to StarCluster checking whether /dev/sd\* exists too quickly.

**Comment by jtriley** [comment]
@srooks10 looks like you were using your new Ubuntu 11.04 HVM-AMI built from your new wiki guide (btw, thanks for contributing your guide!). 

After looking a little deeper I found this on the ec2ubuntu google group:

http://groups.google.com/group/ec2ubuntu/browse_thread/thread/f10205927e884c58/f1d007503bdf9ecd

This seems to imply that /dev/xvd\* is now the standard device name for EBS and /dev/sd\* is no longer supported on Ubuntu 11.04. Now that I know this is the case it should be easy to add a patch for this that supports both the old /dev/sd\* names and the new /dev/xvd\* names.

I'll let you know when there's a patch ready for testing.

**Comment by jtriley** [comment]
@srooks10 this should be fixed, however, would you mind checking out the latest code (in the "develop" branch) and testing whether it works with your custom 11.04 HVM AMI and an EBS volume?

**Comment by srooks10** [comment]
@jtriley I have tested the "develop" branch with my custom 11.04 HVM
AMI and an EBS volume and everything works fine. Thanks a lot.

On Mon, Aug 1, 2011 at 7:57 PM, jtriley
reply@reply.github.com
wrote:

**Comment by jtriley** [comment]
@srooks10 great! glad it's working for you and thanks for testing
