### ISSUE TITLE
VPC security groups seem to be completely open

### ISSUE THREAD

**Issue by delagoya** [jtriley/StarCluster#341]
In SC config I defined security group rules to open ports 80 and 443. 

When I launched a cluster from within an instance in a VPC, the @sc-smallcluster SG seems to have all ports open to the world. I think these were meant to only reference the security group itself instead of 0.0.0.0/0? Here is a copy-paste of the table from the web console 

ICMP
Port (Service)  Source  Action
ALL 0.0.0.0/0   Delete

TCP
Port (Service)  Source  Action
1 - 65535   0.0.0.0/0   Delete
22 (SSH)    0.0.0.0/0   Delete
80 (HTTP)   0.0.0.0/0   Delete
443 (HTTPS) 0.0.0.0/0   Delete

UDP
Port (Service)  Source  Action
1 - 65535   0.0.0.0/0   Delete

**Comment by delagoya** [comment]
I should note that I am using the develop branch commit SHA: 613822af404f77496996a556d0d298e78900e62c

**Comment by jtriley** [comment]
This issue appears to apply to all security groups not just those linked to VPC. Working on a fix now.
