### ISSUE TITLE
Option to associate public IP address with VPC-EC2's ??

### ISSUE THREAD

**Issue by ghost** [jtriley/StarCluster#349]
Is there an option in the Starcluster config file that I can set to allow automatic public IP assignment to VPC-EC2's ?  Or is there another way (besides assigning an Elastic IP to the node) that I can enable automatic public IP assignment to VPC-EC2's.  If not, will there be an option added in the future ?

Specifically in using Starcluster with VPC-EC2's I run into the following problem:  If a public IP isn't assigned to the VPC-EC2 certain API's (like the Ensembl.org API) fail to work for that node.  

A simple solution is to assign and Elastic IP from the AWS console, but these seems unreasonable if you have a large number of worker nodes all trying to access an API with their computations.

If you launch a VPC-EC2 from the AWS console there is a check box option that appears for VPC-EC2's "Public IP" -- "Automatically assign a public IP address to your instance".  Making that check box selection allows an automatically assignment of a public IP address to your VPC-EC2 (static IP not Elastic IP) upon its creation.  I was wondering if I was missing some option in my Starcluster config file that would allow this assignment of a public IP address to VPC-EC2's.

Thanks in advance for the help,

-Jennifer

**Comment by schmutze** [comment]
Hi Jennifer,

If your worker nodes don't need to be directly accessible and only need to initiate outbound connections, one option for you might be to attach a NAT instance to your VPC and have your worker nodes route traffic through it. That way they can communicate to the public internet without needing a static IP.

Here is some documentation that describes such a setup: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_NAT_Instance.html

I hope this helps.
thanks,
chad

**Comment by ghost** [comment]
Thanks. Given Amazon's example for scenario 2, you can use the NAT server to access API without having an public or Elastic IP assigned to the nodes of a starcluster. Using the AWS Scenario 2 as a guide, I was able to configure a starcluster cluster in a similar manner as their Database servers in the example.  You just want to make sure you use the correct ports given the API you are going to use.  I used their VPC Wizard to create the initial NAT EC2.

Thanks for the help,
-Jennifer

**Comment by jtriley** [comment]
@jmstaab StarCluster 0.95 is out now and auto assigns public ips by default for VPC clusters. You can disable this using the new `start` command option `--no-public-ips`. In this case StarCluster must be used from within the VPC in order to connect to the cluster.

**Comment by ghost** [comment]
Thanks, I really appreciate it! Having more than one public IP solves any bottleneck with regards to APIs limiting use of their resources by public IP.  I look forward to testing out Starcluster 0.95 really soon.
-Jennifer
