### ISSUE TITLE
Adding a node of a differnet instance type

### ISSUE THREAD

**Issue by brspurri** [jtriley/StarCluster#369]
Hi there,

The documentation states that we can configure nodes with **multiple instance types**:
http://web.mit.edu/Star/cluster/docs/latest/features.html

But I can't find any example of how to actually do this. Any ideas? Ideally, I would like my master node be a high memory instance, and the worker nodes to be a different type.

Any advice on how to achieve this would be excellent!

**Comment by jtriley** [comment]
@brspurri You can use `master_instance_type` in your cluster config to specify a different instance type from the worker nodes, e.g.:

```
[cluster small]
...
master_instance_type = m1.small
node_instance_type = m1.large
```

You can also do this from the command line:

```
$ starcluster start mycluster --master-instance-type=m1.small --node-instance-type=m1.large
```

There is an additional (and much more complicated!) syntax for node_instance_type when you want to specify multiple instance types for multiple nodes (not just one for master and one for workers). This is rarely used but nevertheless needs to be documented. I'll use this bug as a todo :D

**Comment by nagaflokhu** [comment]
Could someone point me to documentation regarding syntax for specifying multiple node instance types? I haven't been able to find it in the docs.

I would like to have two worker node types, one type with NVIDIA GPUs and the other without. Ideally, the load balancer would be able to distinguish between jobs that require NVIDIA GPUs and jobs that do not, adding the right type of node as needed. Thank you!
