### ISSUE TITLE
volumes not mounting 

### ISSUE THREAD

**Issue by adeslatt** [jtriley/StarCluster#373]
I have two volumes I want to mount -- one volume consistently does not get mounted no matter what I do -- it is a large volume -- 1 TB I don't know if that is contributing to the issue.  
Then when not mounted then it is not nfs served to the other nodes.
In the past I could fix it by removing the nodes and then adding them back on -- but now that does not fix it.
Let me know what you need to reproduce this.

**Comment by jtriley** [comment]
@adeslatt How did you create the volume? Did you format the volume before trying to mount with StarCluster? If not you can create and format a new EBS volume automatically using the `createvolume` command:

```
$ starcluster createvolume <size_in_gb> <zone>
```

(more details here: http://star.mit.edu/cluster/docs/latest/manual/volumes.html#create-and-format-a-new-ebs-volume)

If you already formatted the volume then check the `start` command output for mount errors and also look in `$HOME/.starcluster/logs/debug.log` for the underlying error from the mount command on the cluster. Please paste any relevant errors here.

**Comment by adeslatt** [comment]
The volumes were existing volumes and did not need to be formated.  I resolved the issue by mounting the two separate volumes as follows, in my config file:
One volume is on /mnt
One volume is on /mydata

In my config file I have:
 # list of volumes to attach to the master node (OPTIONAL)  
 # these volumes, if any, will be NFS shared to the worker nodes  
 # see "Configuring EBS Volumes" below on how to define volume sections  
 VOLUMES = smrtanalysis,fofnfiles
 # Sections starting with "volume" define your EBS volumes  
 [volume smrtanalysis]
 # attach vol-c9999999 to /home on master node and NFS-shre to worker nodes  
 VOLUME_ID = vol-c9999999
 MOUNT_PATH = /mnt/
 [volume fofnfiles]
 # attach vol-c9999999 to /home on master node and NFS-shre to worker nodes  
 VOLUME_ID = vol-c9999998
 MOUNT_PATH = /mydata/

NB:  names of volumes redacted and kept to be annonymous.

I had tried to use /opt but that is where the SGE environment is set up and that caused a conflict.
The mydata directory does not need to be created before hand.

This has worked now and is not a problem with the NFS share.

Previously I had mounted to a subdirectory and that must have caused the conflict.
