### ISSUE TITLE
createuser error 0.95.2

### ISSUE THREAD

**Issue by johnbot1** [jtriley/StarCluster#375]
I've encounter a new error with the createuser plugin which did not exist in my previous development installs of star cluster. I've removed and installed the newest release and created a fresh template file with no plugins other than createuser enabled. 

Thanks!
John

http://dpaste.com/hold/1671125/
http://dpaste.com/hold/1671128/

**Comment by jtriley** [comment]
@johnbot1 Fix coming in next 0.95.3 bug fix release.
