### ISSUE TITLE
Add R3 instance types

### ISSUE THREAD

**Issue by delagoya** [jtriley/StarCluster#392]
Would like to request addition of the new R3 instance types. 

http://aws.amazon.com/about-aws/whats-new/2014/04/10/r3-announcing-the-next-generation-of-amazon-ec2-memory-optimized-instances/

Not sure how you want to categorize R3 instance types in starcluster/static.py otherwise I would have just issued a pull request.

**Comment by corydolphin** [comment]
I have created a PR for this change. I am not sure about classification either, please feel free to chime in and correct.

https://github.com/jtriley/StarCluster/pull/393
