### ISSUE TITLE
Starcluster looking for /etc/init.d/portmap instead of new ubuntu-supported rpcbind

### ISSUE THREAD

**Issue by pintohutch** [jtriley/StarCluster#409]
When trying to start up a cluster, I got an error that Starcluster was looking to invoke /etc/init.d/portmap but this command wasn't found. I tried installing portmap via apt-get install portmap, however, ubuntu now defaults to using rpcbind instead. Is there a way around this so that starcluster can work with rpcbind instead? Or is there a way I can force install portmap on Ubuntu 14.04?

**Comment by vasisht** [comment]
The function that starts the NFS server is start_nfs_server in starcluster/node.py. It’s also called from mount_nfs_shares. You could try replacing portmap with rpcbind in those functions.

**Comment by pintohutch** [comment]
Yeah I forked Starcluster and made those changes in my develop branch under
node.py. However I still get an error:
- Starting NFS kernel daemon
  ...done.
  2014-07-17 14:47:39,243 PID: 14254 sshutils.py:561 - DEBUG - executing
  remote command: source /etc/profile && rm -f /etc/exports.d/dummy.exports
  2014-07-17 14:47:39,260 PID: 14254 sshutils.py:585 - DEBUG - output of
  'source /etc/profile && rm -f /etc/exports.d/dummy.exports':

2014-07-17 14:47:39,276 PID: 14254 sshutils.py:561 - DEBUG - executing
remote command: source /etc/profile && rm -rf
/dummy_export_for_broken_init_script
2014-07-17 14:47:39,338 PID: 14254 sshutils.py:585 - DEBUG - output of
'source /etc/profile && rm -rf /dummy_export_for_broken_init_script':

2014-07-17 14:47:39,402 PID: 14254 sshutils.py:561 - DEBUG - executing
remote command: source /etc/profile && exportfs -fra
2014-07-17 14:47:39,420 PID: 14254 sshutils.py:585 - DEBUG - output of
'source /etc/profile && exportfs -fra':

2014-07-17 14:47:39,420 PID: 14254 node.py:667 - DEBUG - Cleaning up
potentially stale NFS entries
2014-07-17 14:47:39,515 PID: 14254 sshutils.py:307 - DEBUG - new
/etc/exports after removing regex (/home node001|/data node001) matches:

# /etc/exports: the access control list for filesystems which may be

exported

# to NFS clients.  See exports(5).

#

# Example for NFSv2 and NFSv3:

# /srv/homes       hostname1(rw,sync,no_subtree_check)

hostname2(ro,sync,no_subtree_check)
#

# Example for NFSv4:

# /srv/nfs4        gss/krb5i(rw,sync,fsid=0,crossmnt,no_subtree_check)

# /srv/nfs4/homes  gss/krb5i(rw,sync,no_subtree_check)

#

2014-07-17 14:47:39,657 PID: 14254 sshutils.py:561 - DEBUG - executing
remote command: source /etc/profile && exportfs -fra
2014-07-17 14:47:39,675 PID: 14254 sshutils.py:585 - DEBUG - output of
'source /etc/profile && exportfs -fra':

2014-07-17 14:47:39,675 PID: 14254 node.py:670 - INFO - Configuring NFS
exports path(s):
/home /data
2014-07-17 14:47:39,832 PID: 14254 sshutils.py:561 - DEBUG - executing
remote command: source /etc/profile && exportfs -fra
2014-07-17 14:47:39,851 PID: 14254 sshutils.py:585 - DEBUG - output of
'source /etc/profile && exportfs -fra':

2014-07-17 14:47:39,851 PID: 14254 clustersetup.py:347 - INFO - Mounting
all NFS export path(s) on 1 worker node(s)
2014-07-17 14:47:39,851 PID: 14254 threadpool.py:168 - DEBUG -
unfinished_tasks = 1
2014-07-17 14:47:39,877 PID: 14254 sshutils.py:561 - DEBUG - executing
remote command: source /etc/profile && /etc/init.d/rpcbind start
2014-07-17 14:47:40,853 PID: 14254 cluster.py:1724 - ERROR - Error occured
while running plugin 'starcluster.clustersetup.DefaultClusterSetup':
2014-07-17 14:47:40,853 PID: 14254 cli.py:284 - ERROR - error occurred in
job (id=node001): remote command 'source /etc/profile &&
/etc/init.d/rpcbind start' failed with status 1:

Traceback (most recent call last):
  File
"/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.5-py2.7.egg/starcluster/threadpool.py",
line 48, in run
    job.run()
  File
"/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.5-py2.7.egg/starcluster/threadpool.py",
line 75, in run
    r = self.method(_self.args, *_self.kwargs)
  File
"/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.5-py2.7.egg/starcluster/node.py",
line 736, in mount_nfs_shares
    self.ssh.execute('/etc/init.d/rpcbind start')
  File
"/usr/local/lib/python2.7/dist-packages/StarCluster-0.95.5-py2.7.egg/starcluster/sshutils.py",
line 578, in execute
    msg, command, exit_status, out_str)
RemoteCommandFailed: remote command 'source /etc/profile &&
/etc/init.d/rpcbind start' failed with status 1:

However, I can run 'source /etc/profile && /etc/init.d/rpcbind start' in
the terminal of either node without getting an error. I believe this is
Starcluster being incompatible with the latest Ubuntu 14.04.

**Comment by pintohutch** [comment]
Actually, I just found a fix that will work:

ln -s /lib/init/upstart-job /etc/init.d/portmap
ln -s /lib/init/upstart-job /etc/init.d/portmap-wait

If you configure your instance/AMI to have a symlink called portmap in the /etc/init.d directory pointing to /lib/init/upstart-job it should work when starcluster configures your cluster.

**Comment by vasisht** [comment]
replacing /etc/init.d..... with service rpcbind start also works.

**Comment by alexbw** [comment]
@vasisht, specifically you  mean replacing
`source /etc/profile && /etc/init.d/rpcbind start`
with
`source /etc/profile && service rpcbind start`
?

**Comment by vasisht** [comment]
Yes, in starcluster/node.py in start_nfs_server and mount_nfs_shares. I prefer 'restart' for both nfs and rpcbind to avoid any issues with a NFS server that's running on node startup (depends on how the AMI was configured).

**Comment by alexbw** [comment]
But a modification to just the AMI, using the symlinks you mentioned above, would not require a fork in starcluster? That might be a preferable fix for me in the short term...

**Comment by vasisht** [comment]
I haven't tried @dclark87 's symlinks but they seemed to work in that instance and will not require any changes to starcluster.

**Comment by hughamacmullaniv** [comment]
@alexbw: for an AMI mod fix to the portmap issue, you might also try:

```
echo "exit 0" > /etc/init.d/portmap
chmod +x /etc/init.d/portmap
```

_Edit_: I take that back ... that's good for RHEL, the above method is the way for Ubuntu:

```
ln -s /lib/init/upstart-job /etc/init.d/portmap
ln -s /lib/init/upstart-job /etc/init.d/portmap-wait
```
