### ISSUE TITLE
configure whether the master is an exec host or not

### ISSUE THREAD

**Issue by delagoya** [jtriley/StarCluster#42]
Feature request: Configure whether the master is part of the exec host list or not. I for one do not want the master as an exec host, letting it concentrate on NFS duties

**Comment by jtriley** [comment]
For your immediate needs I'd recommend a plugin for this as well, however, as mentioned in issue #43, this would be a useful option for an SGE plugin if we decide to go that route.

**Comment by delagoya** [comment]
Yeah, as part of the SGE plugin would be nice.

**Comment by jtriley** [comment]
This is now an option in the "new" SGE plugin:

http://web.mit.edu/star/cluster/docs/latest/plugins/sge.html#using-the-plugin
