### ISSUE TITLE
addnode does not run plugins

### ISSUE THREAD

**Issue by craigbruce** [jtriley/StarCluster#436]
Using 0.95.5 for a cluster on a VPC.

If you run something like: `starcluster addnode mycluster`

I only get this line `>>> Running plugin tagger.TaggerPlugin` when I would expect something like

```
>>> Running plugin tagger 
>>> Tagging all nodes...
>>> Applying tag - owner: craig
>>> Applying tag - dept: development
```

This plugin tags the instances so IAM permissions can be used the terminate only your instances. It work fine with the initial cluster creation, is there something special required of plugins when used with addnode?

**Comment by cancan101** [comment]
When you start the initial cluster, are there any special CL arguments that you are using? Right now the only arguments that get saved and re-used when `addnode` is called are enumerated here: https://github.com/jtriley/StarCluster/blob/e9c633f2d4e64e1dd44df12e10a10b7d5900fac9/starcluster/cluster.py#L689

**Comment by craigbruce** [comment]
I don't think so my cluster is fairly vanilla

```
[cluster smallcluster]
KEYNAME = starcluster-craig 
CLUSTER_SIZE = 2
CLUSTER_USER = sgeadmin
CLUSTER_SHELL = bash
NODE_IMAGE_ID = ami-fdd2c194
NODE_INSTANCE_TYPE = m1.large
SUBNET_ID=subnet-123XYZ
PUBLIC_IPS=False
PLUGINS = tagger 
```

The plugin itself it almost identical to the example in the docs

``` python
# Install this file to $HOME/.starcluster/plugins/tagger.py or somewhere on your $PYTHONPATH
from starcluster.clustersetup import ClusterSetup
from starcluster.logger import log

class TaggerPlugin(ClusterSetup):
    def __init__(self, tags):
        self.tags = eval(tags)

    def run(self, nodes, master, user, user_shell, volumes):
        log.info("Tagging all nodes...")
        for tag in self.tags:
            val = self.tags.get(tag)
            log.info("Applying tag - {0}: {1}".format(tag, val))
            for node in nodes:
                node.add_tag(tag, val)
```

**Comment by cancan101** [comment]
`run` does not get called when adding a node:
https://github.com/jtriley/StarCluster/blob/e9c633f2d4e64e1dd44df12e10a10b7d5900fac9/starcluster/cluster.py#L1042

only `on_add_node`

**Comment by craigbruce** [comment]
I see, I added `on_add_node` and now it works - thanks very much!
