### ISSUE TITLE
master_is_exec_host=False and sge balancer

### ISSUE THREAD

**Issue by cancan101** [jtriley/StarCluster#441]
The SGE balancer dies when trying to add nodes to a cluster with `master_is_exec_host=False` with this message:

```
!!! ERROR - ERROR: Number of slots not consistent across cluster
```

This is caused by the balancer assuming that all nodes have the same number of slots.

**Comment by FinchPowers** [comment]
Do you have the same instance type for master and nodes?

**Comment by cancan101** [comment]
The instance type is the same. It's possible that in my tinkering with `qconf` I did something silly.

**Comment by cancan101** [comment]
Interesting.

It looks like when `master_is_exec_host=False`, then this codes does not run at all for the master:

```
            node.ssh.execute("qconf -aattr hostgroup hostlist %s @allhosts" %
                             node.alias)
            node.ssh.execute('qconf -aattr queue slots "[%s=%d]" all.q' %
                             (node.alias, num_slots))
```

as opposed to running with `num_slots=0`.

**Comment by FinchPowers** [comment]
...various things may cause this. I personally run w/o that check so you can safely comment it out if you want to move forward.

**Comment by cancan101** [comment]
Okay. Will do. I can see what I did, which was to start the cluster with `master_is_exec_host=True` but then I tried to "simulate" `master_is_exec_host=False` by using qconf.

**Comment by FinchPowers** [comment]
Ahh. Then you have to remove master from the exec host list.

**Comment by cancan101** [comment]
Yea. I also created #445 because ultimately what you care about is how many slots will be added by another node.

**Comment by FinchPowers** [comment]
Join #starcluster on irc freenode if you want to talk about it.

**Comment by FinchPowers** [comment]
And possibly close this ticket since it doesn't look like an issue anymore.
