### ISSUE TITLE
NFS server startup error

### ISSUE THREAD

**Issue by mcianfrocco** [jtriley/StarCluster#453]
Hello,

I have an AMI that I using as a template to create a test cluster. The AMI was made from Ubuntu Server 14.04 LTS (HVM) (instance c3.2xlarge).

Upon trying to start the cluster with starcluster, I get the following error message.

Is there is a conflict that might arise between the AMI and the starcluster instances? 

Thanks!
mike

```
$ starcluster start cluster 
StarCluster - (http://star.mit.edu/cluster) (v. 0.95.5)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu
>>> Using default cluster template: smallcluster
>>> Validating cluster template settings...
>>> Cluster template settings are valid
>>> Starting cluster...
>>> Launching a 2-node cluster...
>>> Creating security group @sc-cluster...
>>> Creating placement group @sc-cluster...    
Reservation:r-c46c59ef
Reservation:r-c76e5bec
>>> Waiting for instances to propagate...
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Waiting for cluster to come up... (updating every 30s)
>>> Waiting for all nodes to be in a 'running' state...
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Waiting for SSH to come up on all nodes...
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Waiting for cluster to come up took 1.111 mins
>>> The master node is ec2-54-172-120-23.compute-1.amazonaws.com
>>> Configuring cluster...
>>> Running plugin starcluster.clustersetup.DefaultClusterSetup
>>> Configuring hostnames...
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%      
>>> Creating cluster user: mike (uid: 1001, gid: 1001)
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Configuring scratch space for user(s): mike
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Configuring /etc/hosts on each node
2/2 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Starting NFS server on master
!!! ERROR - Error occured while running plugin 'starcluster.clustersetup.DefaultClusterSetup':
!!! ERROR - remote command 'source /etc/profile && /etc/init.d/nfs
!!! ERROR - start' failed with status 127:
!!! ERROR - bash: /etc/init.d/nfs: No such file or directory
```

**Comment by cancan101** [comment]
See: https://github.com/jtriley/StarCluster/pull/435#issuecomment-55298255

**Comment by mcianfrocco** [comment]
Thanks for the response! 

But, sorry for the newbie question - but which initialization script(s) do I need to change?

**Comment by cancan101** [comment]
https://github.com/jtriley/StarCluster/issues/409#issuecomment-55790719

**Comment by mcianfrocco** [comment]
I'm sorry to keep this issue open, but I still can't seem to get around this NFS error. 

To summarize: I have an AMI that has nfs-kernel-server installed and the following symbolic links:

  ln -s /lib/init/upstart-job /etc/init.d/portmap
  ln -s /lib/init/upstart-job /etc/init.d/portmap-wait

However, I still have the same error when I try to start up my cluster using this AMI. 

This is not to say that I can't start any cluster using starcluster, it's just that when I specify this specific AMI that starcluster crashes during initialization. 

Are there any other strategies that I could take to get around this? I really would like my cluster nodes to have the same environment as this AMI.

**Comment by cancan101** [comment]
What error are you getting now? If the sym linking actually worked I would think you should be getting a different error.

i.e. either /etc/init.d/nfs exists OR you have changed the python to call the correct command.

**Comment by mcianfrocco** [comment]
The symbolic link definitely exists on the AMI, but it's the same error. Is there something I could be missing? 

What if I shared the AMI with you to see if it can work in your hands? 

> > > Starting NFS server on master
> > >   !!! ERROR - Error occured while running plugin 'starcluster.clustersetup.DefaultClusterSetup':
> > >   !!! ERROR - remote command 'source /etc/profile && /etc/init.d/nfs 
> > >   !!! ERROR - start' failed with status 127:
> > >   !!! ERROR - bash: /etc/init.d/nfs: No such file or directory

**Comment by cancan101** [comment]
It looks clear to me that the link does NOT exist.

Either way, you shouldn't need to make a symlink at all. Just change the SC
python to run the service command.

**Comment by mcianfrocco** [comment]
These are the lines that I changed: 

---

[[Within start_nfs_server]]
  704: self.ssh.execute('/etc/init.d/portmap start', ignore_exit_status=True)
to 
  704: self.ssh.execute('service rpcbind start', ignore_exit_status=True)

  718: self.ssh.execute('/etc/init.d/nfs start')
to
  718: self.ssh.execute('service rpcbind start')

---

[[Within mount_nfs_shares]]
  730: self.ssh.execute('/etc/init.d/portmap start')
to
  730:  self.ssh.execute('service rpcbind start')

And this is the error that I got: 

> > > Starting NFS server on master
> > >  !!! ERROR - Error occured while running plugin 'starcluster.clustersetup.DefaultClusterSetup':
> > >  !!! ERROR - remote command 'source /etc/profile && service rpcbind
> > >  !!! ERROR - start' failed with status 1:
> > >  !!! ERROR - start: Job is already running: rpcbind

**Comment by Jspujol** [comment]
I am having the same error. Did you figure out how to solve it?

Thanks in advance!
