### ISSUE TITLE
ERROR - InvalidBlockDeviceMapping

### ISSUE THREAD

**Issue by agmarsh** [jtriley/StarCluster#455]
This is an EC2 response error when initializing a new cluster (v095.5): 

"InvalidBlockDeviceMapping: the encrypted flag cannot be specified since device /dev/sda1 has a snapshot specified."

In CONFIG, an EBS volume is specified and normally "MOUNT_PATH=/home" works. Tried "MOUNT_PATH=/mnt" to bypass /dev/sda1, but same error is generated. Error happens with r3 and m3 master instance types. 

I don't think this is a bug in SC, but some issue in terms of how EC2 is responding to the vol mount request.

**Comment by agmarsh** [comment]
> Just noticed that a boto revision yesterday (08 OCT) included some BlockDevice chages . .  . ?

**Comment by eedlund** [comment]
I have also seen this error when using i2.4xlarge and c3.2xlarge instances.

**Comment by jtriley** [comment]
@agmarsh Which AMI are you using? Also are you using the govcloud region by chance?

**Comment by jtriley** [comment]
@agmarsh Could you also try installing boto==2.25.0 and see if you get the same issue? That should eliminate whether this is the version of boto or something new with the API...

**Comment by agmarsh** [comment]
AMI: ami-52a0c53b
Region is us-east-1a

Will try with boto 2.25 now.

**Comment by agmarsh** [comment]
Cluster setup is successful with boto ver 2.25.0.

**Comment by rpetit3** [comment]
boto==2.25.0 also fixed this issue for me

**Comment by ehlen** [comment]
That worked for me as well.

$ sudo pip uninstall boto
$ sudo pip install boto==2.25

**Comment by jtriley** [comment]
OK - might have to pin boto to 2.25 and do a hotfix release for now. Need more time to investigate what changed in latest boto...

**Comment by vasisht** [comment]
It's working for me with the 2.32.0 version. It fails with an  InvalidBlockDeviceMapping error with 2.33.0. I couldn't find the change log for 2.33.0 on the boto site.

**Comment by jtriley** [comment]
@vasisht Thanks for those details. I'll test with 2.32.0 and release a hotfix that addresses this soon.

**Comment by mortgoldman** [comment]
I believe the problem may be connected to the 2.33.0 release per this line in the boto release notes:  Support EBS encryption in BlockDeviceType. (:issue:`2587`, :issue:`2480`, :sha:`7a39741`)

**Comment by hugomeiland** [comment]
new boto 2.34.0 does not resolve this issue... downgrading to 2.25 still works for me...

**Comment by MichaelWS** [comment]
Still broken for me as well.
