### ISSUE TITLE
ensure ephemeral storage is available by overriding block device mapping when running instances

### ISSUE THREAD

**Issue by jtriley** [jtriley/StarCluster#46]
**From the StarCluster mailing list:**

I would like to use the instance storage (2x 840G disks) that comes
with the cluster compute instance type. This is again for an Ubuntu
11.04 hvm AMI.

The scratch space is not mounted on /mnt:
  root@master:/mnt/sgeadmin# df -h
  Filesystem            Size  Used Avail Use% Mounted on
  /dev/sda1             7.9G  4.0G  3.5G  54% /
  none                   12G  144K   12G   1% /dev
  none                   12G     0   12G   0% /dev/shm
  none                   12G   60K   12G   1% /var/run
  none                   12G     0   12G   0% /var/lock
  /dev/xvdz1             20G  618M   19G   4% /home

The block devices are indeed not available on my AMI:

  ec2-describe-images ami-ab5197c2 -K ~/.starcluster/pk-....pem -C
~/.starcluster/cert-....pem
  IMAGE ami-ab5197c2    11-04-hvm   available   private     x86_64  machine   ebs   hvm
  BLOCKDEVICEMAPPING    /dev/sda1       snap-8f055aee   8

Nor are they on Alestic's public one:

  ec2-describe-images ami-1cad5275 -K ~/.starcluster/pk-....pem -C
~/.starcluster/cert-....pem
  IMAGE ami-1cad5275    099720109477/hvm/ubuntu-images/ubuntu-natty-11.04-amd64-server-20110426 099720109477    available   public      x86_64  machine
  ebs   hvm
  BLOCKDEVICEMAPPING    /dev/sda1       snap-b1ad2dde   8

Would it be possible to add the local instance storage during the AMI
creation with ebsimage ?
http://docs.amazonwebservices.com/AWSEC2/2011-01-01/UserGuide/index.html?Using_AddingDefaultLocalInstanceStorageToAMI.html

**Comment by jtriley** [comment]
Unfortunately this is not possible when creating a new HVM image using the ebsimage command. This is a limitation imposed by EC2's 'create-image' API call. The 'create-image' call does not support specifying a block device mapping that's different from the image host's block device mapping. This is why you don't see the ephemeral storage on your new 11.04 HVM image; the original alestic HVM didn't have it in the block device mapping. To make matters worse the EC2 API documentation specifically states that an HVM image must be created from an existing HVM instance using the 'create-image' API call in order for the AMI to be HVM-compatible:

http://docs.amazonwebservices.com/AWSEC2/latest/UserGuide/using_cluster_computing.html#using_cluster_computing_hvm_ami_running_instance

There may be a way around this though. It is possible to manually specify a block device mapping when launching the instances. This would allow StarCluster to override the default block device mapping specified by a given AMI and always provide ephemeral storage even if the original AMI creator did not include it when registering the image. I'll experiment with this and see what I can come up with.

**Comment by jtriley** [comment]
The biggest issue I see with this is that the AMI's /etc/fstab has to be aware of what the block-device mapping is so that it can mount things properly on boot. I suppose StarCluster could fiddle /etc/fstab to handle its own mapping but that might be tricky and could possibly break a given AMI. This might be useful as an option/flag.

**Comment by delagoya** [comment]
Instance block device mapping on boot of EBS backed images are independent of the AMI. See here for some information on it:

http://ubuntu-smoser.blogspot.com/2011/02/getting-ephemeral-devices-on-ebs-images.html

Boto has support for mounting the ephemeral storage via device block mappings. It should be fairly straight forward to add this into `starcluster.awsutils`. I'll give it a whirl now and report back.

**Comment by jtriley** [comment]
@delagoya Yep, I have a method that will build a boto block device mapping that requests _all_ possible ephemeral drives for any instance type (see EasyEC2.create_root_block_device_map). This method is used in StarCluster when registering new EBS AMIs. You should be able to fetch the block device map using that method, then delete the '/dev/sda1' entry from the map (not needed when launching instances given that AMI already has /dev/sda1 mapping), and then you should be able to use it when launching instances.

With that said, I'm going to test the newest StarCluster Ubuntu11.10 HVM AMI and see if all the ephemeral drives appear. If so then this is pretty much a non-issue given that the 11.10 AMIs already have the proper block-device-mapping meaning all ephemeral drives should show up on the non-HVM StarCluster 11.10 AMIs by default.

One last point is that boto will not _mount_ the ephemeral drives but rather _attach_ them - mounting is still the responsibility of the AMI. I know that Ubuntu's cloud-init, which is active on latest StarCluster 11.10 AMIs, takes care to mount one of the ephemeral drives to /mnt but IIRC the rest are left unmounted and the user is expected to mount them somewhere useful.

**Comment by delagoya** [comment]
Yes I saw the `create_root_block_device_map()` method. I opted to add instance type specific device mappings to static.py though. 

I was going to write a plugin that mounts and formats the volumes as one large RAID on the exec nodes for local scratch space. I find that in the IO intensive analysis I do tend to bring the master NFS to its knees. 

You can see my changes here: https://github.com/delagoya/StarCluster (develop branch)

**Comment by jtriley** [comment]
@delagoya Thanks for your contributions. I really don't believe the instance type device mapping is necessary given that any instance type that doesn't support _all_ ephemeral drives will only use what it has available. Also I prefer to keep from putting boto code in the static module - static is meant to be simple data structures and it also should only import things from Python's stdlib. A better place for your boto code would be in awsutils. With that said I can certainly use the awsutils modifications to allow block device mapping - I will likely cherry-pick this out.

I would definitely be interested in incorporating an ephemeral-raid plugin if you're able to get it working. Keep me posted.

**Comment by delagoya** [comment]
I agree WRT `static.py`, will switch it to how you suggested previously and send in a pull request tomorrow. 

You may also look at the plugin I just made to tweak grid engine to enable h_vmem usage, and to set the number of slots on the master to less than the processors. As I mentioned, my analyses tend to hammer NFS. and I have seen load go to 200% even when only having half the slots. https://github.com/PGFI/StarClusterPlugins/

**Comment by qubole** [comment]
create_root_block_device_map is very useful. is there any particular reason why it's only used in create_image_from_instance_store? (i would like to use it in regular ebs instance creation as well). 

(this is for hadoop type stuff - where the image is ebs - but ephemeral disks are used by hadoop. ebs images are just way faster to create and also boot faster than instance store ones).

**Comment by jtriley** [comment]
@qubole Currently the EBS image creation code uses the extremely simple CreateImage API call which does all the magic for you behind the scenes. While this simplifies the code it doesn't allow customizations of the resulting AMI's settings - it simply adopts the settings of the AMI used by the image host. StarCluster should probably move away from the CreateImage API call and handle the EBS image creation process entirely on its own in the case of EBS-backed image hosts. As you noticed, it's already doing this for instance-store-backed image hosts presently.

I'll file a separate issue for this today unless you beat me to it...

**Comment by jtriley** [comment]
@delagoya Your GridEngine tweaks plugin looks good. I recently moved all SGE-related setup code to a 'new' SGE plugin:

https://github.com/jtriley/StarCluster/blob/develop/starcluster/plugins/sge.py

Would you be interested in merging it with the StarCluster SGE plugin?

**Comment by delagoya** [comment]
yes, planning on it later today. Still need to offer it as a plugin temporarily until next SC release. When or how often do you usually tag an official release?
