### ISSUE TITLE
Error : the encrypted flag cannot be specified since device

### ISSUE THREAD

**Issue by paavalan** [jtriley/StarCluster#464]
Getting Error on starcluster start mycluster

EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidBlockDeviceMapping</Code><Message>the encrypted flag cannot be specified since device /dev/sda1 has a snapshot specified.</Message></Error></Errors><RequestID>88b316a6-6be3-4e14-b1e6-145cb01e951b</RequestID></Response>

**Comment by FinchPowers** [comment]
I get that too since this morning.

**Comment by vasisht** [comment]
It's an issue with boto. Downgrading to boto-2.32.0 resolves the issue.  See the mail threat at http://mailman.mit.edu/pipermail/starcluster/2014-October/002427.html

**Comment by FinchPowers** [comment]
@vasisht Cool thanks! I downgraded to 2.32.1 and it works.

**Comment by paavalan** [comment]
@vasisht Thanks. working now. :+1:
