### ISSUE TITLE
Mounting two partitions from the same volume

### ISSUE THREAD

**Issue by brainfood** [jtriley/StarCluster#47]
Hi jtriley,

I have an EBS volume with two partitions (both formatted). If I am mounting either alone, starcluster starts normally. However, when I try to mount both partitions together, I get the following error: 

!!! ERROR - Multiple configurations for volume vol-####### specified.
!!! ERROR - Please choose one

In the starcluster config file the entries under EBS volumes for these two partitions are completely different, except for the volume ID. For example:

[volume partition-1]
VOLUME_ID = vol-abc123
MOUNT_PATH = /opt/part1/
PARTITION = 1

[volume partition-1]
VOLUME_ID = vol-abc123
MOUNT_PATH = /opt/part2/
PARTITION = 2

Is there a flag I'm missing or some error in the way I'm defining these volumes? Thanks a lot for the help!

-brainfood

**Comment by jtriley** [comment]
Your second volume config _should_ be **[volume partition-2]** instead of **[volume partition-1]** but even with this fix you'll encounter another bug with the current code: starcluster will assume/automatically assign separate devices for each partition which is not correct. I'll try to get a fix for this soon.

**Comment by brainfood** [comment]
Thanks for the response and for catching my typo in the post.

**Comment by jtriley** [comment]
Now that I look at the code, you must have had the volume sections named properly in your config otherwise you wouldn't have received the error. In any event, I need to rework the auto-device-assigning logic in Cluster.load_volumes to handle this use case...

**Comment by jtriley** [comment]
FYI this fix was released in the 0.92 version of StarCluster
