### ISSUE TITLE
'starcluster get' appears to fail for large (for me, at least) data sets

### ISSUE THREAD

**Issue by johnmoore4** [jtriley/StarCluster#485]
I am trying to move data from an ec2 node to my computer over the internet.

I run, for example:

starcluster get mycluster ~/HDG/Navier-Stokes/rae2822/UnsteadyP3RunRe1e5/default.msh_timestep000{000..135}\* .

However, starcluster does nothing despite waiting for 20 or so minutes. If I reduce the number of files transfered, say to the range 000{100..135}, everything works.

Any idea what might be happening here?

Thank you,
John

**Comment by johnmoore4** [comment]
I've checked to see if scp and rsync work, and and they both do. Is there a reason get/put is based on scp instead of rsync?

**Comment by cancan101** [comment]
:+1:  to using `rsync`
