### ISSUE TITLE
Start different cluster with different config file

### ISSUE THREAD

**Issue by shayanshams66** [jtriley/StarCluster#495]

**Comment by erikedlund** [comment]
I use the following:

starcluster --config=/path/to/starcluster/config ...

**Comment by shayanshams66** [comment]
thanks

**Comment by erikedlund** [comment]
Yes, any command given after 

starcluster --config=/path/to/starcluster/config ...

applies the configuration defined in that file to the command you are running. This will not alter or replace the configuration file in the default location.

For example, let's say that I have two AWS accounts. The credentials for the one I use most often are in my default configuration file at /home/user/.starcluster/config and typically I would start a cluster with it by using the normal start command. However, if I want to use my second account for some reason I can make a new configuration file with those credentials and do the same things I normally would, with the exception of adding --config=/path/to/second/config to each command.

**Comment by shayanshams66** [comment]
thanks a million
when I use the mentioned comment it is replying that : config /home/shayan/starcluster exists but is not a regular file  although I just made a directory 2 min ago and its empty

**Comment by jtriley** [comment]
@shayanshams66 the `--config` option expects a file not a directory.

**Comment by shayanshams66** [comment]
I got it gentle men thanks a lot
