### ISSUE TITLE
Enabling DNS_PREFIX removes the functioning of the Put and Get Command

### ISSUE THREAD

**Issue by machbio** [jtriley/StarCluster#501]
Enabling the DNS_PREFIX removes the ability to use the PUT and GET command from the starcluster

```
DNS_PREFIX = True
```

Attached is the error message on the Starcluster 0.95.6

![starclsuter_dnsprefix](https://cloud.githubusercontent.com/assets/1488387/6084056/b12c7004-adfb-11e4-8b90-b4926f7cb100.png)

**Comment by egvalentejr** [comment]
I see the same problem. It works if you use the syntax that allows you to name the node
ex:
starcluster put i02dvt3 --node i02dvt3-master ./test.txt ~
StarCluster - (http://star.mit.edu/cluster) (v. 0.95.6)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

test.txt 100% ||||||||||||||||||||||||||||||||||||||| Time: 00:00:00 111.11 K/s

**Comment by fabregaszy** [comment]
Ran into the same issue today, work around as the second thread.
Command `sshmaster` has no such issue.
