### ISSUE TITLE
add quickstart for parallel ipython plugins to docs

### ISSUE THREAD

**Issue by jtriley** [jtriley/StarCluster#51]

**Comment by ogrisel** [comment]
And also update the `IPython.parallel` tutorial & documentation to point to it.

**Comment by jtriley** [comment]
I've merged @minrk's ipcluster updates and also updated the ipcluster plugin docs which gives a quick guide on how to use the IPy cluster after the plugin has completed successfully. This will be included in the next 0.92.2 release along with a new set of AMIs containing IPython 0.11.

@minrk, could we link to StarCluster's ipcluster docs as a quick-and-easy-on-ec2 link from IPython's docs some where?

**Comment by minrk** [comment]
Absolutely, I will make sure to do that.  Is there somewhere in particular I should point them, or just to the starcluster docs frontpage?

**Comment by jtriley** [comment]
@minrk Awesome, thanks. We should link to: 

http://web.mit.edu/starcluster/docs/latest/plugins/ipython.html

This page will be updated with the latest ipcluster docs once 0.92.2 and new 11.10 AMIs are released. You can see what's currently planned to be there now at:

https://github.com/jtriley/StarCluster/blob/develop/docs/sphinx/plugins/ipython.rst

Let me know if you have suggestions/feedback...

Thanks!

**Comment by jtriley** [comment]
@minrk I've released StarCluster 0.93 (decided to skip 0.92.2 since there's enough new stuff). Could we put a link to the IPython plugin doc (http://web.mit.edu/starcluster/docs/latest/plugins/ipython.html) somewhere in IPython's docs and/or website? BTW the new plugin includes notebook support which is _really_ cool and new 11.10 AMIs have latest 0.12 release...

**Comment by minrk** [comment]
Awesome!  IPython docs do [mention starcluster](http://ipython.org/ipython-doc/dev/parallel/parallel_process.html#ipython-on-ec2-with-starcluster).

**Comment by jtriley** [comment]
@minrk Fantastic, thanks for your help and for contributing the updates to the ipcluster plugin!
