### ISSUE TITLE
StarCluster AMIs are incompatible with t1.micro

### ISSUE THREAD

**Issue by npinto** [jtriley/StarCluster#52]
There seems to be an issue when trying t1.micro with StarCluster AMIs, e.g.:

```
% ec2-run-instances -key kp ami-bf5eb9d6 -t t1.micro
Client.UnsupportedOperation: AMI 'ami-bf5eb9d6' with an instance-store
root device is not supported for the instance type 't1.micro'.
```

FYI, the same error was experienced in CS264 (but no answer was given the student):
http://forum.cs264.org/index.php?topic=411.0

**Comment by jtriley** [comment]
An EBS-backed AMI must be used with the t1.micro instance type. I'll push out public EBS AMIs in us-east zone soon...

**Comment by npinto** [comment]
Awesome! Thanks @jtriley!

**Comment by jtriley** [comment]
Done, latest AMIs are out. Use 'starcluster listpublic' in any AWS region to find the new EBS-backed Ubuntu 11.10-based StarCluster AMIs (including new HVM w/ GPU tools)
