### ISSUE TITLE
s3image hangs at "Bundling image file..."

### ISSUE THREAD

**Issue by yina** [jtriley/StarCluster#53]
Started up a cluster with command:
$ starcluster start -o -s 1 -i m1.small -n ami-8cf913e5 imagehost

Logged in with command:
$ starcluster sshmaster imagehost

Generate an AMI with s3image with command:
$ starcluster -d s3image i-XXXXXXX my-new-image <my-uniq-bucket>

stdout will get to "Bundling image file..." and then hang. When inspecting the master node, the ec2-bundle-vol process has ended and all the my-new-image.part files are created. The next command is not executed.  Any help would be appreciated.

notes:
- the ssh client has NOT timed out as ssh process is still visible on the master.
- as far as I can tell, the next commands should be ec2-upload-bundle and ec2-register. these commands are not executed.
- running 0.92rc2
- creating an ebsimage works without a problem.

**Comment by yina** [comment]
Has anyone replicated this bug?

**Comment by jtriley** [comment]
@yina, sorry to hear you're having issues with the s3image command. have you tried running the same s3image command multiple times to see if a subsequent run succeeds? running the command again should clean-up old image files and try again. 

also, i believe you're correct that the ec2-bundle-vol command has finished but just for drill how are you verifying this? I typically use "pgrep -lf ec2-bundle-vol". in general the ec2-bundle-vol command takes a while as it has to rsync and tar the entire root disk and then split the tar'd file up into multiple chunks to upload to S3. you can check if these processes are running using "pgrep -lf rsync" and "pgrep -lf tar". if they are then ec2-bundle-vol definitely hasn't finished...

I'm trying to release 0.92 of StarCluster tonight, just finishing up docs. I'll try the s3image command using that same API and see if I can reproduce the issue.

**Comment by yina** [comment]
thanks justin. no worries. i just created an ebsimage and am working on that. thanks again for an excellent package, it is quite useful for the work I'm doing.

in regards to your questions:
- i've run the command about 10 times and it hangs at the same spot.
- i verified that the bundle command has stopped with ps-ef.  also the /mnt directory has all of the split up files and no further files are produced. i can't quite remember about rsync and tar but i'll check it out again to be sure. i did run the command overnight and it hung at the same spot.

if I get a chance, i'll see if I can fork the project and poke around in the source to see what's going on. please let me know if you have any luck reproducing the bug.  thanks again.

**Comment by jtriley** [comment]
@yina, glad to hear ebsimage is at least working for you in the mean time. I have an instance running now using the ami-8cf913e5 AMI and I'm testing the s3image command now:

```
% starcluster s3image i-08e4d368 deletemenow deletemebucket
StarCluster - (http://web.mit.edu/starcluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

>>> Creating bucket deletemebucket
>>> Checking for EC2 API tools...
pk-blahblah.pem 100% |||||||| Time: 00:00:00   0.00 B/s
cert-blahblah.pem 100% |||||| Time: 00:00:00   0.00 B/s
>>> Removing private data...
>>> Creating the bundled image: (please be patient)
Copying / into the image file /mnt/deletemenow...
Excluding: 
     /sys/kernel/debug
     /var/lib/nfs/rpc_pipefs
     /sys/kernel/security
     /sys
     /proc/fs/nfsd
     /proc
     /dev/pts
     /dev
     /dev
     /media
     /mnt
     /proc
     /sys
     /etc/udev/rules.d/70-persistent-net.rules
     /etc/udev/rules.d/z25_persistent-net.rules
     /root/.ssh
     /mnt/deletemenow
     /mnt/img-mnt
1+0 records in
1+0 records out
1048576 bytes (1.0 MB) copied, 0.00235968 s, 444 MB/s
mke2fs 1.41.11 (14-Mar-2010)
warning: Unable to get device geometry for /mnt/deletemenow
```

Is this where you were hanging at? This is still running for me so I'll post an update if/when it finishes...

**Comment by yina** [comment]
no it goes on to the next output of "Bundling image file..."

**Comment by jtriley** [comment]
OK, it's at that point now and ec2-bundle-vol is still running. we'll see what happens...

**Comment by jtriley** [comment]
Hmmm, OK it just finished for me no problems although I am using the latest dev version, however, that portion of the code hasn't really changed since 0.92rc2.

It took about 50 minutes all together and created ~251 part files. Keep in mind this is a clean instance that I used s3image on, I didn't install anything additional so it may take longer if you installed a ton of extra software.

```
Splitting /mnt/deletemenow.tar.gz.enc...
Created deletemenow.part.000
Created deletemenow.part.001
...
Created deletemenow.part.251
Generating digests for each part...
Digests generated.
Unable to read instance meta-data for ramdisk-id
Unable to read instance meta-data for product-codes
Creating bundle manifest...
ec2-bundle-vol complete.
>>> Cleaning up...
>>> _bundle_image took 44.161 mins
>>> Uploading bundled image: (please be patient)
Uploading bundled image parts to the S3 bucket deletemebucket ...
Uploaded deletemenow.part.000
Uploaded deletemenow.part.001
....
Uploaded deletemenow.part.251
Uploading manifest ...
Uploaded manifest.
Bundle upload completed.
>>> _upload_image took 4.966 mins
>>> create_image took 49.208 mins
>>> Your new AMI id is: ami-blahblah
```

At this point you can either install the latest code from github and try it again or wait until I release tonight or tomorrow and try with the latest stable version. I appreciate your help testing and getting this resolved given that s3image is a pretty major command that should work for everyone.

**Comment by yina** [comment]
thanks for testing the code out. I'll wait for the release and let you know whether it works. yin

**Comment by yina** [comment]
Justin, I am closing this ticket. I was able to create an s3image using the s3image command. Not sure why it didn't work previously, but for now this is great. Thanks again for your help. Yin

**Comment by jtriley** [comment]
OK, no problem, not sure what the issue was but glad it's working for you now. FYI the new 0.92 release is out:

http://pypi.python.org/pypi/StarCluster
http://web.mit.edu/stardev/cluster/downloads.html
