### ISSUE TITLE
Specified configuration files are not used for: starcluster start

### ISSUE THREAD

**Issue by mza** [jtriley/StarCluster#55]
Hello,

I've spotted a problem when starting a new cluster from the command line while specifying a configuration file. Starcluster doesn't use the specified configuration file. For example:

$ starcluster -c /user/other-location/config start clustername

or

$ starcluster --config=/user/other-location/config start clustername

Results in:

starcluster.exception.ConfigNotFound: config file /user/.starcluster/config does not exist

The same approach works with other commands, such as listclusters.

I spotted in the source that the start command adds another -c mapping to the action options (-c or --cluster-template) for specifying a cluster template. Could this be overwriting the global options somehow?

Many thanks!

~ Matt @ AWS

**Comment by jtriley** [comment]
@mza thanks for reporting, I'm looking into this now

**Comment by jtriley** [comment]
OK, I see the issue, it's because of the way I'm handling shell completion[1] when setting up the opts for the start command. This is why you don't see the issue with other commands. I'll fix this before I release 0.92.1 today.

[1] http://web.mit.edu/stardev/cluster/docs/latest/manual/shell_completion.html

**Comment by mza** [comment]
Awesome - thanks!

Indeed, I fixed it in my own fork by removing the shell completion features.

**Comment by jtriley** [comment]
Just leaving this open until I close with a commit...

**Comment by jtriley** [comment]
@mza fyi this fix is included in the [latest 0.92.1 release](http://pypi.python.org/pypi/StarCluster/0.92.1).
