### ISSUE TITLE
Add support for new instance type m4.10xlarge

### ISSUE THREAD

**Issue by andrewrech** [jtriley/StarCluster#559]
Hello,

Can you please consider adding the new instance type, mx.10xlarge (1), to the list of allowed instance types in static.py? Thank you!

(1) https://aws.amazon.com/blogs/aws/the-new-m4-instance-type-bonus-price-reduction-on-m3-c4/

**Comment by FinchPowers** [comment]
https://github.com/jtriley/StarCluster/pull/560

**Comment by jtriley** [comment]
Done in #560

**Comment by andrewrech** [comment]
Whoops sorry thanks
