### ISSUE TITLE
files not shared across cluster - why?

### ISSUE THREAD

**Issue by mwcrepeau** [jtriley/StarCluster#579]
I'm trying starcluster for the first time and the first thing I did was start up a small cluster following the instructions in the starcluster website video.  My cluster isn't behaving as described.  In the video, when a file is created on the master machine (touch thisfile) it can be seen on the other node (ssh node001 ls thisfile).  But when I try this I get the following error message:

ls: cannot access thisfile: No such file or directory

Am I missing something?

**Comment by mwcrepeau** [comment]
Wait a minute.  Actually it works if I su to sgeadmin.

**Comment by machbio** [comment]
@mwcrepeau Close this Issues - as its resolved.
