### ISSUE TITLE
MPI hello world program return error result

### ISSUE THREAD

**Issue by xiongjie494** [jtriley/StarCluster#591]
I started a cluster of 2 nodes successfully. I try to run a MPI hello world program to check the cluster. But the result display that there are only master node is working in the cluster.

//////////////////////////////////////////
//MPI_Hello.c
//////////////////////////////////////////
# include <mpi.h>
# include <stdio.h>

int main(int argc, char*\* argv) {
    // Initialize the MPI environment
    MPI_Init(NULL, NULL);

```
// Get the number of processes
int world_size;
MPI_Comm_size(MPI_COMM_WORLD, &world_size);

// Get the rank of the process
int world_rank;
MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

// Get the name of the processor
char processor_name[MPI_MAX_PROCESSOR_NAME];
int name_len;
MPI_Get_processor_name(processor_name, &name_len);

// Print off a hello world message
printf("Hello world from processor %s, rank %d"
       " out of %d processors\n",
       processor_name, world_rank, world_size);

// Finalize the MPI environment.
MPI_Finalize();
```

}

$ mpicc MPI_Hello.c -o hello
$ mpirun -np 2 ./hello

RESULTS:
Hello world from processor master, rank 0 out of 1 processors
Hello world from processor master, rank 0 out of 1 processors

It seams only master is in the cluster. 
I choose the NODE_IMAGE_ID = ami-6b211202,  NODE_INSTANCE_TYPE = t2.micro, and put the config file in attachment.

I have no idea what happened. Please help me out. Thank you! 

[config.pdf](https://github.com/jtriley/StarCluster/files/460810/config.pdf)

**Comment by vasisht** [comment]
Have you tried using the MPICH2 plugin?
http://star.mit.edu/cluster/docs/0.93.3/plugins/mpich2.html

**Comment by xiongjie494** [comment]
No. I just use the OpenMPI.

**Comment by xiongjie494** [comment]
Thank you, vasisht. I try using MPICH2, it works! I got the right result.
