### ISSUE TITLE
listclusters command could show configured clusters

### ISSUE THREAD

**Issue by godber** [jtriley/StarCluster#6]
The listclusters command currently only shows running clusters, it could show both running and configured clusters so that there is an easy way to remember which clusternames you have defined when you go to launch a cluster.

In fact, the start command printout could show the user their list of configured clusters when explaining that a cluster tag is a required argument for starting a cluster.

This is very minor and a feature request rather than an issue.

**Comment by godber** [comment]
the stop command could list running clusters when run without an argument.

**Comment by jtriley** [comment]
These are great ideas and sorry it's taken me forever to get around to responding. I'm game with updating the start/stop usage messages with available templates/running clusters respectively. Working on that now and will close this bug when it's done.

However, I think having listclusters show the available templates would be a bit overloaded but I do like the idea of having a quick way at looking at the configuration without a text editor or cat-ing/grep-ing yourself. I'm thinking of adding a 'config' command that will show you a list of any type of config section (e.g. plugins, volumes, clusters, etc):

**List all config sections of a given type**:

```
$ starcluster config list cluster
smallcluster
mediumcluster
largecluster
```

```
$ starcluster config list plugin
ipcluster
tmux
```

**Show a given section or multiple sections**:

```
$ starcluster config show cluster smallcluster mediumcluster largecluster
[cluster smallcluster]
cluster_size = 3
node_instance_type = m1.small
node_image_id = ami-small
plugins = ipcluster, tmux

[cluster mediumcluster]
extends = smallcluster
cluster_size = 5
node_instance_type = m1.large
node_image_id = ami-medium

[cluster largecluster]
extends = smallcluster
cluster_size = 10
node_instance_type = cg1.4xlarge
node_image_id = ami-large
```

```
$ starcluster config show plugin ipcluster
[plugin ipcluster]
setup_class = starcluster.plugins.ipcluster.IPCluster
```

What do you think?
