### ISSUE TITLE
addnode with spot pricing requests wrong number of instances

### ISSUE THREAD

**Issue by qubole** [jtriley/StarCluster#62]
> > > Launching node(s): node002, node003, node004, node005, node006
> > > SpotInstanceRequest:sir-df40260a
> > > SpotInstanceRequest:sir-adb9a40a
> > > SpotInstanceRequest:sir-8337fe0a
> > > SpotInstanceRequest:sir-32025c0a
> > > SpotInstanceRequest:sir-9173dc0a
> > > SpotInstanceRequest:sir-f472360e
> > > SpotInstanceRequest:sir-ada8b40e
> > > SpotInstanceRequest:sir-a9ae240e
> > > SpotInstanceRequest:sir-fdc0700e
> > > SpotInstanceRequest:sir-c373a40e
> > > SpotInstanceRequest:sir-2d43fe0a
> > > SpotInstanceRequest:sir-2311900a
> > > SpotInstanceRequest:sir-35f45e0a
> > > SpotInstanceRequest:sir-3eaa4c0a
> > > SpotInstanceRequest:sir-dfceca0a
> > > SpotInstanceRequest:sir-6764740e
> > > SpotInstanceRequest:sir-4a070c0e
> > > SpotInstanceRequest:sir-f3dd840e
> > > SpotInstanceRequest:sir-3f357e0e
> > > SpotInstanceRequest:sir-b98e520e
> > > SpotInstanceRequest:sir-e94eda0a
> > > SpotInstanceRequest:sir-a83eaa0a
> > > SpotInstanceRequest:sir-8070c60a
> > > SpotInstanceRequest:sir-88c82e0a
> > > SpotInstanceRequest:sir-865eb80a

it's N^2 instances :-).

**Comment by qubole** [comment]
reason is:

kwargs = dict(price=spot_bid, instance_type=instance_type,
                      min_count=count, max_count=count, count=count,
                      key_name=self.keyname, security_groups=[cluster_sg],
                      availability_zone_group=cluster_sg,
                      launch_group=cluster_sg, placement=zone or self.zone,
                      user_data='|'.join(aliases),
                      placement_group=placement_group)
        resvs = []
        if spot_bid:
            for alias in aliases:
                kwargs['user_data'] = alias
                resvs.extend(self.ec2.request_instances(image_id, **kwargs))

kwargs for each request needs to have count etc. to be set to 1 i suppose (not yet tested)

**Comment by jtriley** [comment]
@qubole Thanks for reporting. I'm working on a patch now. If you could test after I close this bug with a commit that'd be great.
