### ISSUE TITLE
issue in SGE loadbalance command

### ISSUE THREAD

**Issue by jtriley** [jtriley/StarCluster#65]
http://mailman.mit.edu/pipermail/starcluster/2012-January/000974.html

**Comment by rayrayson** [comment]
In the log file:

2012-01-17 22:45:35,668 PID: 9177 ssh.py:531 - ERROR - command 'source /etc/profile && qhost -xml' failed with status 1
2012-01-17 22:45:35,669 PID: 9177 ssh.py:536 - DEBUG - error: failed receiving gdi request response for mid=1 (got syncron message receive timeout error).

So qhost -xml exits with 1, and the error message is "error: failed receiving gdi request response for mid=1 (got syncron message receive timeout error)." Whenever communication error occurs, then qhost prints the error and exits...

I think we should add some code in get_stats() & run(), such that when an error occurs in qhost, qstat, or qacct, the error is handled.

In get_stats():

```
qhostxml = '\n'.join(master.ssh.execute(...))
if master.ssh.get_last_status() != 0:
    return 1

qstatxml = '\n'.join(master.ssh.execute(...))
if master.ssh.get_last_status() != 0:
    return 1

qacct = '\n'.join(master.ssh.execute(...))
if master.ssh.get_last_status() != 0:
    return 1
```

In run() in balancers/sge/**init**.py:

```
ret = self.get_stats()
if ret == 1:
   time.sleep(self.polling_interval)
   continue

if ret == -1:
   log.error("Failed to get stats. LoadBalancer is terminating")
   return
```

We should also add a counter to check if the error repeatedly occurs, and if so, exit the load balancer.

**Comment by jtriley** [comment]
Excellent, thanks for the tips. I'll try to come up with a patch in the next day or two if you don't beat me to it :D

**Comment by jtriley** [comment]
Working on this now, will close with a commit.
