### ISSUE TITLE
Verify existence of keyfiles prior to AMI launch

### ISSUE THREAD

**Issue by godber** [jtriley/StarCluster#8]
Apologies if this is fixed in git, but the paths to the keyfiles should be tested prior to the launch of an AMI.  I don't know if its tested prior to launch of a cluster, but I know that with createvolume on 0.91 it  does not.

Austin

**Comment by jtriley** [comment]
Yes, the keyname/key_location settings are tested prior to launch of a cluster, however, you're right about the createvolume command.

**Comment by jtriley** [comment]
fix bug with keyname loading in cluster.get_cluster

use explicit deps list in setup.py

add "stopped" to list of allowable states when looking for worker nodes
in a cluster. this allows 'seeing' stopped ebs nodes in the cluster's
security group

add ssh_to_node convenience method to Cluster class

tell user that there are lingering instances in the case of
shutdown_instance = False in VolumeCreator class

check that keypair/key_location exists in VolumeCreator class

raise exception if not ebs-backed instance in EasyEC2.migrate_image function

allow cc1.4xlarge in instance types list (instance type still not fully
supported yet)

closed by 9fc7eac08c2a59d970912cacd7cb4b2a6729acb5
