### ISSUE TITLE
Make starcluster AMIs that allow you to launch the new GPU instances

### ISSUE THREAD

**Issue by treelinelabs** [jtriley/StarCluster#9]

**Comment by jtriley** [comment]
this is in progress. basically just need to install nvidia drivers/cuda/pycuda/etc

**Comment by jtriley** [comment]
made the ami, need to release new version so that starcluster can actually launch clusters of gpu/cluster compute types. 0.91.2 version is not compatible with new cluster compute/gpu types yet but github code _is_

**Comment by apatil** [comment]
Would you be able to share the ami ID before the new release?

**Comment by jtriley** [comment]
yes, enough folks are requesting it. going to give it one more run through and clean things up and then I'll make it public. hopefully tonight or tomorrow. i'll post the AMI here and to the starcluster/pycuda lists when it's ready.

**Comment by jtriley** [comment]
Here it is folks: ami-12b6477b

This AMI contains the following GPU software in addition to the usual StarCluster stack:
- NVIDIA Driver 260.19.21
- NVIDIA Cuda Toolkit 3.2 (cublas, cufft, curand)
- PyCuda and PyOpenCL (recent git checkouts)
- MAGMA 1.0-rc2

This AMI is currently not compatible with StarCluster 0.91.2, however, if you just want to play around with the new GPU instances you're probably better off launching a single instance from the AWS management console. If you need a GPU cluster the latest github code does work with this new AMI and instance type (both cg1.4xlarge and cc1.4xlarge) if you're interested in testing.

A few notes:
1. CUDA is installed in /usr/local/cuda
2. MAGMA (shared) library is installed in /usr/local/magma
3. Custom python2.6 installation in /usr/lib64/python2.6/site-packages
4. NumPy/SciPy/PyCuda/PyOpenCL/etc are installed in the custom python2.6 installation
5. All software sources used are in /usr/local/src (also look here for PyCuda/PyOpenCL/MAGMA examples, etc)

Let me know if you have issues...
