### ISSUE TITLE
start cluster fails with TypeError

### ISSUE THREAD

**Issue by jvimal** [jtriley/StarCluster#90]
I get this crash dump when I try to start a new cluster using a new cluster template...   It looks like the "self.refresh_interval" somehow becomes none.  Not sure why!

```
2012-03-10 18:04:46,074 PID: 28796 cli.py:287 - DEBUG - Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/cli.py", line 255, in main
    sc.execute(args)
  File "/Library/Python/2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/commands/start.py", line 193, in execute
    validate_running=validate_running)
  File "/Library/Python/2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/cluster.py", line 1414, in start
    return self._start(create=create, create_only=create_only)
  File "<string>", line 2, in _start
  File "/Library/Python/2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/utils.py", line 87, in wrap_f
    res = func(*arg, **kargs)
  File "/Library/Python/2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/cluster.py", line 1437, in _start
    self.setup_cluster()
  File "/Library/Python/2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/cluster.py", line 1445, in setup_cluster
    self.wait_for_cluster()
  File "<string>", line 2, in wait_for_cluster
  File "/Library/Python/2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/utils.py", line 87, in wrap_f
    res = func(*arg, **kargs)
  File "/Library/Python/2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/cluster.py", line 1239, in wait_for_cluster
    self.wait_for_running_instances()
  File "/Library/Python/2.6/site-packages/StarCluster-0.9999-py2.6.egg/starcluster/cluster.py", line 1203, in wait_for_running_instances
    time.sleep(self.refresh_interval)
TypeError: a float is required

---------- SYSTEM INFO ----------
StarCluster: 0.9999
Python: 2.6.1 (r261:67515, Jun 24 2010, 21:47:49)  [GCC 4.2.1 (Apple Inc. build 5646)]
Platform: Darwin-10.8.0-i386-64bit
boto: 2.2.2
ssh: 1.7.13
Crypto: 2.4.1
jinja2: 2.6
decorator: 3.3.1
```

**Comment by jtriley** [comment]
@jvimal Looks like you're using the development version. When was the last time you pulled the latest changes from git?

**Comment by jvimal** [comment]
@jtriley: March 9th.  My HEAD is 58baea8d366481c705429ef3317a3fc5a31e2b5b.

**Comment by jtriley** [comment]
@jvimal Hmmmm, I'm unable to reproduce this just starting a cluster using:

```
$ starcluster start -c mediumcluster mycluster
```

If you can, please provide the following:
1. The exact command you're using. This is printed at the very top of the crash report (prefixed with "COMMAND:")
2. A minimal config that produces the error. Remember to remove all private data from the config before posting!

This will help me track down the issue faster.

**Comment by jvimal** [comment]
@jtriley: Sorry, here is the complete command:

`$ starcluster start s0 -s 2 -c small`

The config file is:

```
[aws info]
aws_access_key_id = xxx
aws_secret_access_key = xxx
aws_user_id = xxxx-xxxx-xxxx
aws_region_name = us-west-2a
aws_region_host = ec2.us-west-2.amazonaws.com

[key aws]
key_location = ~/.ssh/aws.rsa

[keypair west2]
key_location = ~/.ssh/aws-west.pem

[volume data]
volume_id = vol-xxx
mount_path = /data

[cluster small]
keyname = west2
cluster_user = root
cluster_size = 10
cluster_shell = bash
master_image_id = ami-8ef27fbe
master_instance_type = m1.small
node_image_id = ami-8ef27fbe
node_instance_type = m1.small
availability_zone = us-west-2a
volumes = data
```

**Comment by jtriley** [comment]
I can't reproduce this using the exact config you posted and substituting the relevant settings. I was able to start a cluster no problem (see output below). Also, a couple notes on your config:
1. `cluster_user` should never be 'root' (this is why the useradd/groupadd commands fail in the output below) - I'm going to update the validation to raise an error before launching the cluster when `cluster_user=root`.
2. The reason NFS and SGE setup fails in the output below is because of the AMI you're using. This may change in the future but for now StarCluster expects NFS/SGE to already be installed/unpacked on the AMI. You can fix this simply by using one of the StarCluster AMIs instead (see `starcluster listpublic`). If you really need to use that AMI I would recommend installing the NFS packages on it and rebundling using the `ebsimage` command (see http://web.mit.edu/star/cluster/docs/latest/manual/create_new_ami.html).

```
% starcluster start s0 -s 1 -c small
StarCluster - (http://web.mit.edu/starcluster) (v. 0.9999)
Software Tools for Academics and Researchers (STAR)
Please submit bug reports to starcluster@mit.edu

>>> Validating cluster template settings...
>>> Cluster template settings are valid
>>> Starting cluster...
>>> Launching a 1-node cluster...
>>> Creating security group @sc-s0...
Reservation:r-0ade8d3a
>>> Waiting for cluster to come up... (updating every 30s)
>>> Waiting for all nodes to be in a 'running' state...
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Waiting for SSH to come up on all nodes...
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Waiting for cluster to come up took 1.193 mins
>>> The master node is ec2-50-112-50-203.us-west-2.compute.amazonaws.com
>>> Setting up the cluster...
>>> Configuring hostnames...
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Creating cluster user: None (uid: 1000, gid: 1000)
!!! ERROR - command 'groupadd -o -g 1000 root' failed with status 9    |   0%  
!!! ERROR - command 'useradd -o -u 1000 -g 1000 -s `which bash` -m root' failed with status 6
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Configuring scratch space for user(s): root
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Configuring /etc/hosts on each node
1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
>>> Starting NFS server on master
!!! ERROR - command '/etc/init.d/portmap start' failed with status 127
!!! ERROR - command '/etc/init.d/nfs start' failed with status 127
!!! ERROR - command '/usr/sbin/exportfs -fra' failed with status 127
>>> Setting up NFS took 0.022 mins
>>> Configuring passwordless ssh for root
>>> Configuring passwordless ssh for root
>>> Shutting down threads...
20/20 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100%  
!!! ERROR - SGE is not installed on this AMI, skipping...
>>> Configuring cluster took 0.395 mins
>>> Starting cluster took 1.648 mins
```

**Comment by jtriley** [comment]
@jvimal Just for drill would you mind installing the latest stable version using easy_install/pip and see if the bug still exists? Also if you installed from github using "python setup.py install" you need to re-run that every time you "pull" updates - please try this too if you haven't already.

**Comment by jvimal** [comment]
@jtriley: Thanks, I changed the config to use correct AMI and username.  I am fine with Ubuntu; I just wanted a Debian based distro! :)

Btw, I pulled and installed develop again, and I encountered the same bug.   I also encountered it with the stable branch installed with easy_install.   I made this change and things worked.  (cluster started, and I am able to ssh to the nodes)

I am running on Mac OSX 10.6 with python 2.6.1, if that's relevant?

``` python
In file starcluster/cluster.py:
    @print_timing("Waiting for cluster to come up")
    def wait_for_cluster(self, msg="Waiting for cluster to come up..."):
        # [ ... snip ... ]
        interval = self.refresh_interval
        # I added the lines below as interval was "None"
        if interval is None:
            self.refresh_interval = 5
            interval = 5
```

**Comment by jtriley** [comment]
@jvimal I'm also on OSX 10.6 but using 2.7 - building a virtualenv now for 2.6 to see how it goes. Glad the patch works but there's an underlying bug somewhere up the chain that needs to be fixed. Are you on IRC by chance? I'm on #starcluster on freenode if you'd like to debug in real time.

**Comment by jtriley** [comment]
I wonder if manually specifying the refresh interval works? Try this without
your patch:

```
$ starcluster start -c small -s 2 -r 30 s0
```

**Comment by jtriley** [comment]
#starcluster irc ftw!

We discovered this happens when `[global]` section isn't defined in the config due to a bug in starcluster/commands/start.py. I wasn't removing my old [global] section when creating a 'minimal' config which is why I wasn't able to reproduce this :/ Fix coming soon.
